### ISSUE TITLE
Migration Value for unique fields

### ISSUE THREAD

**Issue by sedubois** [graphcool/console#1004]
<img width="273" alt="screen shot 2017-05-24 at 11 13 53" src="https://cloud.githubusercontent.com/assets/4217871/26398703/3087a35e-4072-11e7-923f-831c360fe456.png">

I had a pre-existing type `Author` with different fields, and was trying to add a new field `fullName` of type String, required, migration value "-", default value untouched (`null`), and unique constraint. Then I hit "Create field" and got the error above.

**Comment by sedubois** [comment]
By removing the unique constraint, I could create the field. It looks like the unique constraint might be the source of various issues both with wizard and with schema editor (#994).

**Comment by sedubois** [comment]
It's probably because the migration value is the same for all entries, so isn't unique. But the console should make a better job of conveying that instead of internal server error. It should also be possible to provide a migration value unique to each entry.

**Comment by sedubois** [comment]
Ideally, the wizard could allow to recombine other fields to build the migration value. For example, if a type `Author` already has fields `firstName` and `lastName`, when adding a field `fullName`, the migration value could be `${firstname} ${lastName}`. But it might need more complex logic for less trivial cases (e.g type casting, getting value from a relation, etc). Maybe allow user to build a graphQL query on the concerned node...

**Comment by marktani** [comment]
Thanks for the feedback! For now, we improved the error message to this:

> 'fullName' has more than one entry and can't be added as a unique field with a non-unique value.

A better migration experience will be possible once we added the feature to use a function when migrating a field: https://github.com/graphcool/feature-requests/issues/67 Let's continue the discussion there 🙂.
