### ISSUE TITLE
Default permission query incomplete

### ISSUE THREAD

**Issue by schickling** [graphcool/console#1009]
The default permission query no longer includes the `$node_id` etc.

![image](https://cloud.githubusercontent.com/assets/1567498/26443346/412ba96e-4138-11e7-867a-f0c84f000fb1.png)

**Comment by timsuchanek** [comment]
The `create` permission doesn't contain the `$node_id` at all, `update` and `delete` do. I removed the `$node_id` for `create` from the sidebar so it doesn't seem that it's available
