### ISSUE TITLE
Selection order not taken into account in multiple relations

### ISSUE THREAD

**Issue by sedubois** [graphcool/console#1016]
I have a one-to-many relation. Using the console, I add a value for this field by clicking it then selecting the relevant data from the popup, but the order of elements doesn't seem to be influenced by my selection order. I need the elements to be in a precise order.

**Comment by marktani** [comment]
Relations don't guarantee any ordering. If you need a special order you can either use a list String field and store an ordered list of ids, or add an integer `position` on the "many-side" and use the `orderBy` field argument:

```
query {
  allParents {
    id
    children (orderBy: position_ASC) {
      id
    }
  }
}
```

**Comment by sedubois** [comment]
Thanks @marktani I'll try to workaround the issue as you suggested. (As mentioned in https://github.com/graphcool/feature-requests/issues/116 I still think that the ordering should rather be a property of the relation itself.)

**Comment by marktani** [comment]
Great! If that doesn't work out, let's continue the discussion there.
