### ISSUE TITLE
After I login in, I only see a blank screen

### ISSUE THREAD

**Issue by brene** [graphcool/console#1018]
![image](https://cloud.githubusercontent.com/assets/4989523/26492123/f1de3b8e-4212-11e7-8c94-b395ae2ef1a9.png)

**Comment by brene** [comment]
This seems to only repro if I go to console.graph.cool/login directly. If I go to console.graph.cool/ it works fine.

**Comment by timsuchanek** [comment]
Thanks for reporting @brene ! Fix is deployed to master
