### ISSUE TITLE
CORS error when executing function

### ISSUE THREAD

**Issue by pbassut** [graphcool/console#1033]
This is what I get on the console when trying to execute a function:
```
Fetch API cannot load https://d0b5iw4041.execute-api.eu-west-1.amazonaws.com/prod/execute/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://console.graph.cool' is therefore not allowed access. The response had HTTP status code 504. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
fullscreen:1 Uncaught (in promise) TypeError: Failed to fetch
```

It was working fine yesterday with the very same function but now it hangs for a while and then gives me that error.

OS: macOS Sierra
Browser: Chrome 58.0.3029.110 (64-bit)

**Comment by pbassut** [comment]
I'm making a request to another domain in my code. That's probably why the CORS error.

Making requests elsewhere should be supported, right?

**Comment by marktani** [comment]
> Making requests elsewhere should be supported, right?
Yes. What happens when you trigger the function with a mutation?

**Comment by pbassut** [comment]
With an actual mutation and not test data it works fine.

**Comment by marktani** [comment]
This is actually an issue in the backend, so I moved it over to here: https://github.com/graphcool/api-bugs/issues/83
