### ISSUE TITLE
Can't "Define Rules" on Permissions from Safari

### ISSUE THREAD

**Issue by enricenrich** [graphcool/console#1035]
As the title says, we can't "Define Rules" on Permissions on Safari. It works on Chrome. I attach an screenshot so you can see exactly what happens (or what doesn't happen 😝).

By the way, I have macOS 10.12.5 with Safari 10.1.1.

<img width="757" alt="screen shot 2017-05-30 at 01 27 19" src="https://cloud.githubusercontent.com/assets/357265/26563748/6b105534-44d7-11e7-9021-86078ebdae54.png">

**Comment by marktani** [comment]
related to #871
