### ISSUE TITLE
Permission query rewritten when using $now custom variable

### ISSUE THREAD

**Issue by xiplias** [graphcool/console#1041]
Hi

If following permission query is saved on a Type:
```
query ($now: DateTime!) {
  SomeUserExists(
    filter: {
      createdAt_gt: $now
    }
  )
}
```

When going into the editor again the query has changed to:
```
{
  SomeUserExists(
    filter: {
      createdAt_gt: $now
    }
  )
}
```

Is this an error in the editor? Or am I just not using it correctly?

Based on following documentation: 
https://www.graph.cool/docs/reference/auth/permission-queries-iox3aqu0ee/

**Comment by marktani** [comment]
`$now` is not available yet, I created this feature request to stay notified of our progres: https://github.com/graphcool/feature-requests/issues/222
