### ISSUE TITLE
The “Test Run” button in the functions dialog is not available in safari

### ISSUE THREAD

**Issue by artyomchel** [graphcool/console#1057]
![screen shot 2017-06-06 at 5 19 52 pm](https://user-images.githubusercontent.com/28609290/26837621-3441b48c-4ade-11e7-8597-17a3ebcf73d0.png)

**Comment by marktani** [comment]
The screenshot you shared should not contain a Test Run button. Is the Test Run button available once you click on Fullscreen Mode?

**Comment by artyomchel** [comment]
The Run & Edit button is available in the video, however: https://www.graph.cool/docs/tutorials/validation-and-transformation-with-rp-zeez7aiph3/

Is the video just out of date?

Test Run button is available in fullscreen mode.

**Comment by marktani** [comment]
> Is the video just out of date?

Indeed! Closing this 🙂
