### ISSUE TITLE
Creating a POST model gets you stuck in the onboarding

### ISSUE THREAD

**Issue by marktani** [graphcool/console#1068]
It looks like the name is transferred to `Post` before creation, but it's not registered and the step is not updated.

**Comment by timsuchanek** [comment]
We need more information on why it's stuck. We have now ci set up of the onboarding, which can run through the onboarding correctly currently

**Comment by marktani** [comment]
Sorry for not being clear before. If you name the model `POST` instead of `Post`, you get stuck.

**Comment by timsuchanek** [comment]
ah ok :D will fix it
