### ISSUE TITLE
Some changes in graphql on Schema View fail without error or with incorrect error

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/console#1076]
When making changes directly to the schema, some changes are not handled correctly:

- Changing the name of a system field. When changing the name of a system field, you can preview, and apply changes. No error message is shown and the change is not applied.

- Changing the name of a relation field. Throws an error, but with a confusing message: "You can only create scalar fields and 'Post' is not a scalar value. Did you intend to create a relation?". I'm not creating a field, or a relation, I'm just renaming the field.

**Comment by timsuchanek** [comment]
This is a backend related issue, which we persist in our `api-bugs` repo. I just moved it here: https://github.com/graphcool/api-bugs/issues/104
