### ISSUE TITLE
Renaming field on relation shows incorrect error message

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/console#1077]
When renaming a field on a relation, as soon as you click edit on the field name, a validation error pops up which is incorrect.
1. Field names don't have to be unique across the project.
2. Showing a validation error before a change has even been made by the user is not nice.
![image](https://user-images.githubusercontent.com/852069/27002156-c150277a-4dd9-11e7-8be7-1b3bbfedc189.png)

**Comment by timsuchanek** [comment]
Thats a good point! I will fix that right today
