### ISSUE TITLE
Schema editor asks for migrationValue when it doesn't need to

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/console#1080]
- If no nodes exists for a Type, and you **change** a field to required using the schema editor, that change applies correctly.

- If nodes exists for a Type, the schema editor **always** asks for a migration value, even though all nodes have a value in that field.

- If you change a field from required to not required, the editor also asks for a migration value, which is incorrect.

- If you change the field type, the editor **always** asks for a migration value, even if the change would not cause any data loss (like: from Int to String). This one is the worst, because in this case, the migration value is **always** applied to every node, causing data loss!

Please improve the check to only require a migrationvalue for new, required fields on Types with existing nodes, and on changing a field **to** required if there are nodes with null values in that field.

Bonus feature request: add the '@migrationValue' attribute automatically, just like the '@rename' is added automatically when you change the name of a field.

**Comment by timsuchanek** [comment]
Awesome, I see you're finding a lot of edge cases of the schema editor, that's really valuable for us!
I separated your bonus feature request to #1082

**Comment by timsuchanek** [comment]
Moved it to https://github.com/graphcool/api-bugs/issues/105
