### ISSUE TITLE
Inconsistent behavior between schema editor and type editor GUI when changing data types

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/console#1081]
In the schema editor, when changing datatypes, you have to provide a migrationValue, and ALL node values will be overwritten (see #1080 last point).

If you use the type editor GUI to change the data type, you also get a warning that all values will be replaced by the migration value. But you can't specify a migration value, and the change is applied preserving all data if the data allows it.
![image](https://user-images.githubusercontent.com/852069/27002304-ede2ce00-4dde-11e7-8bea-9f985eab4f77.png)

However, if the data does not allow the data type change (for example: string to int with incompatible field values), and internal error occurs.
![image](https://user-images.githubusercontent.com/852069/27002321-2fa307c4-4ddf-11e7-9bd5-615d15bd55ab.png)

**Comment by timsuchanek** [comment]
Thanks for making us aware of this one. We have 2 seperate issues here:
1. unify migrationValue behavior between schema editor / field popup
2. we should handle that case better in the backend and not just send a 500

**Comment by timsuchanek** [comment]
Moved to https://github.com/graphcool/api-bugs/issues/106
