### ISSUE TITLE
Webhook URL keeps disappearing in function editor

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/console#1086]
- Open the editor for an inline function (not webhook)
- Switch to webhook, enter a URL.
- Switch back to inline, then webhook again
- URL is gone

If the function is already a webhook function when opening, then the url does not disappear when switching between inline and webhook in the editor.

**Comment by timsuchanek** [comment]
This is indeed a weird behavior. Should be consistent for both cases.
