### ISSUE TITLE
Something weird happens in the background when opening Algolia integration settings

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/console#1111]
![image](https://user-images.githubusercontent.com/852069/27013265-eb98714c-4ee0-11e7-8971-69979180719d.png)

**Comment by timsuchanek** [comment]
What do you mean with something weird happens? I think in your screen you can already see the empty algolia view in the background

**Comment by kbrandwijk** [comment]
Never mind, I didn't recognize it, because none of the other popups in the console blur the background like that. After continuing, I saw it was that screen.
