### ISSUE TITLE
Returned error is not reflected in test run

### ISSUE THREAD

**Issue by marktani** [graphcool/console#1124]
**What is the current behavior?**
Running this function in test run

```js
// Click "EXAMPLE EVENT" to see whats in `event`
module.exports = function (event) {
  return {error: 'error!'}
}
```

does not show any error in the log:

![image](https://user-images.githubusercontent.com/1780597/27134924-80d22536-5117-11e7-8d77-d2da92c10d28.png)

**What is the expected behavior?**

The log on the right side should signify an errorneous execution.

**Comment by timsuchanek** [comment]
Fixed. We also should educate people on how the error format should look like, so that GraphQL Clients can use that error.
For example should the response field afaik be called `errors: []` instead of `error: "string"`

**Comment by marktani** [comment]
The `error` you return in a function is translated to a GraphQL error as described [here](https://www.graph.cool/docs/reference/functions/error-handling-quawa7aed0/).
