### ISSUE TITLE
Incorrect validation message on long project name

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/console#1162]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
If the project name you enter is too long, the validation message says: "The project name must begin with an uppercase letter".

**What is the expected behavior?**
Get a different validation message

**Which browser and OS are affected by this issue? Did this work in previous versions of the Console?**
Win 7 Ent SP1 (64-bit)
Chrome 58.0.3029.110 (64-bit)

**Comment by marktani** [comment]
Added a comment to #805.
