### ISSUE TITLE
Add textual edit mode for Enums

### ISSUE THREAD

**Issue by marktani** [graphcool/console#1171]
**Do you want to request a *feature* or report a *bug*?**  

Feature

**What is the current behavior?**

You can create enums only with the UI.

**What is the expected behavior?**

You can also create enums using the textual mode.

**Comment by kbrandwijk** [comment]
Seems to work now, but the UI is not updated when changes are made in textual mode.

**Comment by timsuchanek** [comment]
Seems to be fixed now

**Comment by marktani** [comment]
Can confirm.
