### ISSUE TITLE
Playground "query variables" box is not visible

### ISSUE THREAD

**Issue by JensMadsen** [graphcool/console#1182]
**Do you want to request a *feature* or report a *bug*?**  
bug
(If this is a *usage question*, please **do not post it here**—post it in our [Forum](https://www.graph.cool/forum/) instead.
If this is not a “feature” or a “bug”, or the phrase “How do I...?” applies, then it's probably a usage question.)

**What is the current behavior?**
see attahced screenshot

**If the current behavior is a bug, please provide the steps to reproduce and if possible screenshots.**
write a new query

**What is the expected behavior?**
field should be visible 

**Which browser and OS are affected by this issue?
ubuntu Chrome Version 59.0.3071.115 (Official Build) (64-bit)
 Did this work in previous versions of the Console?**
![image](https://user-images.githubusercontent.com/6726111/27682137-cefd9bea-5cc1-11e7-9d66-3a489039d073.png)

**Comment by marktani** [comment]
You need to drag the "Query Variables" box upwards. You can also simply click the "Query Variables" label to open or close it: https://i.gyazo.com/542314215c1de5925cdf249dfb559942.gif

I created this ui-feedback, let's discuss this topic there: https://github.com/graphcool/ui-feedback/issues/57 🙂
