### ISSUE TITLE
Can toggle 'Apply to whole type' on Types with only read-only fields

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/console#1202]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
On a Type with only read-only fields, you can toggle 'Apply to whole type', which doesn't affect anything. Also, permissions are never shown with 'in all fields' regardless of this setting.
![rofields](https://user-images.githubusercontent.com/852069/27990323-05dc256c-6453-11e7-8dae-9baa80ba7ee7.gif)

**What is the expected behavior?**
Shouldn't be able to disable 'Apply to whole type'.

**Comment by marktani** [comment]
> which doesn't affect anything

That's not correct. "Apply to whole type" means that the permission applies to all future fields as well. As such, this is intended behaviour.

**Comment by kbrandwijk** [comment]
@marktani Thank you for the explanation.
>Also, permissions are never shown with 'in all fields' regardless of this setting.

That would still be nice.
