### ISSUE TITLE
Disabling Anonymous Auth not removing fields from User

### ISSUE THREAD

**Issue by chrish-21** [graphcool/console#1217]
**What is the current behavior?**
When Anonymous Auth is activated the fields 'secret' and 'isVerified' get added to the User type. When Anonymous Auth is deactivated again the following message appears:

'No package with name "anonymous-auth-provider"'

Also the fields 'secret' and 'isVerified' remain on the User type and are not removed (as is the case with the email auth provider)

**Which browser and OS are affected by this issue? Did this work in previous versions of the Console?**
Windows 10/Chrome

**Comment by marktani** [comment]
Thanks for your input! However, this is intended behaviour and won't be changed 🙂
