### ISSUE TITLE
Can't start onboarding project

### ISSUE THREAD

**Issue by spences10** [graphcool/console#1241]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Onboarding page download `React + Relay` project
![image](https://user-images.githubusercontent.com/234708/28543772-c7f75c7c-70b8-11e7-8758-08044f35fa33.png)

```shell
npm install
npm start
```

I get the following error when the localhost://3000 page opens:

![image](https://user-images.githubusercontent.com/234708/28543793-e441c66a-70b8-11e7-9cfa-72e2c511ffb1.png)

**EDIT:** It looks like it got bored waiting for me to fix the issue and showed me this:
![image](https://user-images.githubusercontent.com/234708/28544533-72d6fcd6-70bb-11e7-8dd0-1e6329708437.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible screenshots.**
See above

**What is the expected behavior?**
Run the project?

**Which browser and OS are affected by this issue? Did this work in previous versions of the Console?**
Chrome
Windows 10

**Comment by marktani** [comment]
Sorry, we need to adjust the instructions for the Relay example like this:

```sh
npm install
npm relay # invoke relay compiler
npm start
```

**Comment by spences10** [comment]
Is there anything else to the onboarding after that? 

It looks like [from the congratualtions message] I completed what I need to without actually doing anything? Is that section on a deley or a timer, I'm sure I didn't do anything to trigger the completion dialog.

**Comment by marktani** [comment]
The congratulations message should only pop up once you made the first request to your endpoint - not exactly sure what happened here 🙂

**Comment by spences10** [comment]
The page was left open whilst I tried to troubleshoot the issue then it just randomly played the congratulations sound which made me jump out of my skin whilst I was looking at something else! lol!!
