### ISSUE TITLE
gravatar npm module not available

### ISSUE THREAD

**Issue by cyrus-za** [graphcool/console#1246]
As requested via https://github.com/graphcool/console/issues/1244#issuecomment-318180366 I am logging a new issue for this.

**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Not all npm modules are available when using `require()`. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible screenshots.**
```javascript
// Click "EXAMPLE EVENT" to see whats in `event`
module.exports = function (event) {
  var gravatar = require('gravatar');
  console.log(gravatar) // Object {}
  console.log(gravatar.url) // undefined
  return {data: event.data}
}

```

**What is the expected behavior?**
It should log a function for `gravatar.url`.

**Comment by kbrandwijk** [comment]
If `console.log(gravatar)` returns `Object{}`, then the require actually works. I suppose you need to do something else, before the `url` property is set.

**Comment by cyrus-za** [comment]
That's just a example. You can pretty much replace it with any package.

**Comment by kbrandwijk** [comment]
Well... @marktani interpreted this as being specifically about gravatar, given the title. Also, all issues relating to npm modules have almost all been contributed to something else by now. So if you have a specific module that doesn't work, I would suggest using that in the bug report, and not one that actually works... Because I have yet to run into a module that does not work because of something on the Graphcool side.

**Comment by marktani** [comment]
![image](https://user-images.githubusercontent.com/1780597/28685320-b02727d4-7307-11e7-8d2c-1509700f667f.png)

It works for me in test run and with a real execution, triggered by a mutation.

**Comment by marktani** [comment]
However, `gravatar` and `gravatar.url` are indeed printed as `{}` and `undefined` for me:

![image](https://user-images.githubusercontent.com/1780597/28685418-f6d9ad96-7307-11e7-8f8a-71b89cfb9ccc.png)

**Comment by kbrandwijk** [comment]
Which they also would in any normal JS environment. Both make perfect sense: https://github.com/emerleite/node-gravatar/blob/master/lib/gravatar.js#L29-L48

**Comment by marktani** [comment]
I can't make the link between your shared file and the observed behaviour. I know that in the browser, a function should be printed when `gravatar.url` is logged. Is that not the case for a node environment? 🤔

**Comment by kbrandwijk** [comment]
![image](https://user-images.githubusercontent.com/852069/28686755-9f4ddffc-730c-11e7-9334-0adeb4d5a591.png)

**Comment by marktani** [comment]
Funny. Is there any name about this/more resources on this specific behaviour?

back to topic: all is working as expected, so I'm closing this issue. If you have other specific npm modules that don't work for you, @cyrus-za, please open another issue in the `api-bugs` repo [here](https://github.com/graphcool/api-bugs/issues/).

**Comment by kbrandwijk** [comment]
Offtopic: Compare the previous output to this:
![image](https://user-images.githubusercontent.com/852069/28687052-8c809df0-730d-11e7-91c2-19ef09c3bf8c.png)

**Comment by cyrus-za** [comment]
ah ok so it doesn't toString like the browser. That makes sense. It's just rather difficult to debug if we cant even log it to console. When I run a function and it doesnt work I got no clue where to start. There are no errors on the screen or any way for me to see what went wrong

**Comment by marktani** [comment]
That's a good point @cyrus-za! It would be very helpful if you create [a new feature request](https://github.com/graphcool/feature-requests) that contains a detailed suggestion of `console.log` should behave in your opinion, maybe even include a resource on how this is solved elsewhere. This could start a very interesting discussion 🙂

**Comment by kbrandwijk** [comment]
@cyrus-za @marktani I noticed this FR coming in: https://github.com/graphcool/feature-requests/issues/336. It's also related to improving function logging, so maybe this can be combined there?

**Comment by cyrus-za** [comment]
Thanks @kbrandwijk I will leave it to that FR then
