### ISSUE TITLE
Account page doesn't work

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/console#1269]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Account page is blank.

**What is the expected behavior?**
It shouldn't be.

**Which browser and OS are affected by this issue? Did this work in previous versions of the Console?**
Win 7 Ent SP1 (64-bit)
Chrome 58.0.3029.110 (64-bit)

Yes.

**Comment by kbrandwijk** [comment]
?
![image](https://user-images.githubusercontent.com/852069/29178669-8edf07d6-7df2-11e7-91a0-fc9ede09a415.png)

**Comment by timsuchanek** [comment]
Can you try to hard refresh? It should show the account settings like it used to 
![image](https://user-images.githubusercontent.com/1094804/29182035-946810e8-7dfd-11e7-8fb2-6ae60240f2a2.png)

**Comment by kbrandwijk** [comment]
Yeah, by now it does...
