### ISSUE TITLE
Updating a description of a type requires refresh

### ISSUE THREAD

**Issue by marktani** [graphcool/console#1275]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

Updating a description of a type requires refresh

**If the current behavior is a bug, please provide the steps to reproduce and if possible screenshots.**

initial state:

![image](https://user-images.githubusercontent.com/1780597/29178571-368699aa-7df2-11e7-8b32-059a5b7cabf9.png)

before hitting enter:

![image](https://user-images.githubusercontent.com/1780597/29178585-41f5336e-7df2-11e7-9a67-aed68e3079a2.png)

after hitting enter:

![image](https://user-images.githubusercontent.com/1780597/29178571-368699aa-7df2-11e7-8b32-059a5b7cabf9.png)

after refresh:

![image](https://user-images.githubusercontent.com/1780597/29178593-4c385766-7df2-11e7-95d5-e722bd81fd36.png)

**What is the expected behavior?**

The description should immediately update.

**Comment by kbrandwijk** [comment]
Related refresh issue: https://github.com/graphcool/console/issues/1267
