### ISSUE TITLE
Sidebar collapses incorrectly

### ISSUE THREAD

**Issue by mattfysh** [graphcool/console#1287]
**Do you want to request a *feature* or report a *bug*?**  
Bugs x2

**What is the current behavior?**

1. When you collapse the sidebar, and return to the console (eg. refresh the page) the full-width sidebars renders inside the collapsed sidebar view
2. Deleting a function doesn’t update the UI, the loading indicator appears and then vanishes but the function is not gone. Attempting to hit Delete again throws an error, since it has already been deleted on the backend

**If the current behavior is a bug, please provide the steps to reproduce and if possible screenshots.**

Detailed in current behaviour section

**What is the expected behavior?**

Should be clear?

**Which browser and OS are affected by this issue? Did this work in previous versions of the Console?**

Latest chrome

**Comment by mattfysh** [comment]
I was able to delete a function just now, and the popup closed + function removed from list, this fixes issue (2)

However issue (1) still persists

**Comment by kbrandwijk** [comment]
1 is probably a duplicate of https://github.com/graphcool/ui-feedback/issues/48

**Comment by mattfysh** [comment]
@kbrandwijk correct - closing this now that 2 is fixed and 1 is covered in that ticket.
