### ISSUE TITLE
Text does not wrap properly in when defining permissions

### ISSUE THREAD

**Issue by artivilla** [graphcool/console#1296]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Image enclosed. Pointing to the issue.

<img width="986" alt="permissions___graphcool" src="https://user-images.githubusercontent.com/2120159/29932394-2efb87da-8e42-11e7-9c7c-75bd5f764b3b.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible screenshots.**
Create some model and try to set permissions. Using a macpro 13".

**What is the expected behavior?**

**Which browser and OS are affected by this issue? Did this work in previous versions of the Console?**
Chrome. macOS Sierra v10.12.6 (16G29). This is my first project.

**Comment by kbrandwijk** [comment]
Seems duplicate of https://github.com/graphcool/console/issues/1096

**Comment by artivilla** [comment]
Oops, closing then.
