### ISSUE TITLE
New types created via the console don't include `createdAt` or `updatedAt`

### ISSUE THREAD

**Issue by lewisblackwood** [graphcool/console#1311]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

Creating a new type via the console does not include the `createdAt` or the `updatedAt` fields on the type.

**If the current behavior is a bug, please provide the steps to reproduce and if possible screenshots.**

This is what my most recently created type looks like:

![type](https://user-images.githubusercontent.com/10392867/30754209-d06c09ae-9fb9-11e7-90e0-a60a2d7e0885.jpg)

If I try to query the `createdAt` field in the playground, I get the error:

```
{
  "data": null,
  "errors": [
    {
      "message": "Cannot query field 'createdAt' on type 'PendingHire'. (line 3, column 5):\n    createdAt\n    ^",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    }
  ]
}
```

**What is the expected behavior?**

My previously created types all included `createdAt` and `updatedAt` by default. I think this behaviour started a couple of days ago.

**Which browser and OS are affected by this issue? Did this work in previous  versions of the Console?**

I'm on Chrome Version 61.0.3163.91.

**Comment by marktani** [comment]
Thanks for bringing this up - we actually changed this recently, as mentioned here: https://github.com/graphcool/graphcool/issues/452#issuecomment-331499705 I also explained there how adding/removing these fields works.

I'll also include this in the next changelog (hopefully next monday) 🙂

**Comment by DevanB** [comment]
@marktani FYI - documentation still states it's included by default: https://www.graph.cool/docs/reference/schema/system-artifacts-uhieg2shio/

**Comment by marktani** [comment]
Thanks, just created this issue: https://github.com/graphcool/content/issues/294 :D

**Comment by lewisblackwood** [comment]
@marktani thanks for the heads up! I hadn't spotted that issue.

**Comment by lewisblackwood** [comment]
@marktani thanks for the heads up! 👍

I think the UI for this could possibly be improved beyond adding the field `createdAt: DateTime!` manually. Maybe a button next to `Add Field` and `Add Relation`?

Also, for most users I would imagine they'd like these fields by default - I might be wrong. It would be cool to configure this in our settings (e.g. "Add `createdAt` and `updatedAt` by default").
