### ISSUE TITLE
Changing relation field to scalar field results in internal server error

### ISSUE THREAD

**Issue by marktani** [graphcool/console#181]
When I click the edit button of a relation field in the data browser and change the field type to any scalar field, an internal server error is returned.

The edit button for relations should probably redirect to the Relation editor and not the Field editor.

**Comment by timsuchanek** [comment]
Oops wrong issue closed

**Comment by timsuchanek** [comment]
Just realized, that this is just not possible anymore with the new Relation popup we have already in production :D
