### ISSUE TITLE
Action Creation Dialog hard to read

### ISSUE THREAD

**Issue by marktani** [graphcool/console#190]
![new-action](https://cloud.githubusercontent.com/assets/1780597/18608441/8e1c18b2-7ce9-11e6-93ce-327c71571cc3.png)

especially the Mutation items are hard to read

**Comment by brene** [comment]
You beat the placeholder? or the white color

**Comment by marktani** [comment]
I mean the items in the drop down list, in particular the blue selection with blue background  and the Grey letters with blue background

**Comment by brene** [comment]
Ah :D I just realized that that's not the case in Chrome and Safari on macOS @julianbauer can you help us out with this?

**Comment by timsuchanek** [comment]
Should be fixed, @marktani please give me feedback for linux, as I can't test it here
