### ISSUE TITLE
Pressing escape should close popups

### ISSUE THREAD

**Issue by schickling** [graphcool/console#203]
Obviously a user should be prompted if changes would be lost.

**Comment by brene** [comment]
Not as easy as I thought originally. Relay somehow cancels a request, when the user presses "Esc". Then  Relay enters into an inconsistent state. I couldn't find anything like this in the Relay issues, so I guess we'll need to investigate this further.

**Comment by timsuchanek** [comment]
First set of popups covered by a83af76.
The rest will be done, when we redo all popups with `react-modal`
