### ISSUE TITLE
Disable data filtering when hiding the filter input fields

### ISSUE THREAD

**Issue by schickling** [graphcool/console#204]

**Comment by brene** [comment]
To implement this we need to refactor the way we handle lokka etc. in Redux. Because currently you have to pass on a lot of additional data that should be miscellaneous if the redux state had it in itself.

**Comment by timsuchanek** [comment]
While implementing this, we need to keep in mind, that when the search input is opened again, the search query should be cached.

Considering that, it doesn't make a lot of sense in the search, as we would have to cache the search query and then reapply. Is somehow not logic as the value is still in the input, the input is just not visible.

If this comes up again, we can repoen this issue.
