### ISSUE TITLE
Columns are in a different order when adding nodes

### ISSUE THREAD

**Issue by marktani** [graphcool/console#210]
In the normal view:

![link-order-1](https://cloud.githubusercontent.com/assets/1780597/18766113/f24fb6e4-8118-11e6-8b1c-6013127ed43a.png)

When adding a node:
![link-order-2](https://cloud.githubusercontent.com/assets/1780597/18766121/f7a61606-8118-11e6-812a-99465d21bf5f.png)

As you can see, another column containing of type integer is suddenly the first column when adding a node.

The columns in the normal view are sorted descending alphabetically, while the columns when adding a node are sorted ascending alphabetically.

**Comment by marktani** [comment]
the process of adding a new node is also almost impossible to finish... to change my cursor in another cell I have to click Set To Null first, only then will I be able to click on another cell. If I click on another cell before, nothing happens and my cursor is still in the integer cell

**Comment by schickling** [comment]
#211 should be a temporary fix for this until #51 is implemented.
