### ISSUE TITLE
Field Popup: Entering Field Names UX

### ISSUE THREAD

**Issue by idkjs** [graphcool/console#212]
When you enter a screen name the wrong way you get a not so descriptive error. In the top left. Screenshot attached.  I would say that the placeholder text in the input box being capitalized might be misleading as well. The info popup referencing camel case is super light. I would suggest making it darker. Doesnt hurt for user to know that help is available. 
![graphcool2](https://cloud.githubusercontent.com/assets/2370391/18784685/f08c475c-8193-11e6-9eeb-f751939e1870.PNG)
![graphcool1](https://cloud.githubusercontent.com/assets/2370391/18784686/f08c837a-8193-11e6-9999-cd88a23b468e.PNG)

**Comment by timsuchanek** [comment]
Resolved in the new popup
