### ISSUE TITLE
Field popup: Migration value info is wrong

### ISSUE THREAD

**Issue by sorenbs** [graphcool/console#218]
When changing a field to be required and nodes already exist, the migration value checkbox is automatically selected and the info box displays this scary warning:

![image](https://cloud.githubusercontent.com/assets/281337/18867558/0297b260-84a5-11e6-9012-f013f84efe8d.png)

It is not correct though as only null values are replaced with the migration value.

Please note that if you change the type of the field, we do in fact overwrite all existing values.

**Comment by timsuchanek** [comment]
Done in new popup
