### ISSUE TITLE
Password manager compatibility

### ISSUE THREAD

**Issue by schickling** [graphcool/console#227]
> my password manager doesn't detect the login form, it's probably missing some login/password tags

Thanks to @sedubois for reporting this!

**Comment by brene** [comment]
@sedubois what password manager are you using? We want to recreate this :-)

**Comment by schickling** [comment]
@sedubois can you check if this now works for you?

**Comment by sedubois** [comment]
I see the new Auth0-lock login screen and I can log in that way, but unfortunately my password manager doesn't prefill it. That's probably out of your hands, though...

**Comment by schickling** [comment]
I see. Thanks for the quick update. On the long-term, we'll implement our own login screen in order to replace Auth0 lock. This way we can pre-render it which should enable this functionality.

**Comment by timsuchanek** [comment]
It's an issue of `auth-lock`, here is the related issue https://github.com/auth0/lock/issues/857
