### ISSUE TITLE
"copy example value" button doesn't work for imageUrl

### ISSUE THREAD

**Issue by schickling** [graphcool/console#228]
Thanks to @sedubois for reporting this!

**Comment by brene** [comment]
@sedubois it would be great to know which browser you used :)

**Comment by sedubois** [comment]
Sure @brene, was Chrome 53.0.2785.116 (64-bit) 😊

**Comment by marktani** [comment]
see also #359

**Comment by timsuchanek** [comment]
Already fixed in the latest console
