### ISSUE TITLE
Don't display user email on dashboard

### ISSUE THREAD

**Issue by sedubois** [graphcool/console#237]
If you wish users to share screenshots of their dahboards for bug reporting purposes etc, then their email shouldn't be visible in the top right of the dashboard.

**Comment by schickling** [comment]
@julianbauer Maybe we'll go for the name instead?
Would that solve the problem for you @sedubois?

**Comment by brene** [comment]
The thing is that we actually already use the name of the user. If you haven't set the name, it'll default to the email.

**Comment by sedubois** [comment]
Interesting, my email was put in both the name and email fields (probably because @schickling created my account manually that way). However, even when setting my full name in the name field and saving, even after refresh, and even after logout/login, it's still my email which displays in top right.

Once that is fixed to display my name as intended, it would probably be useful to make entering the name compulsory when registering. Then no need to fall back on displaying email.

**Comment by schickling** [comment]
This should be fixed based on the new the design. Please reopen if this is still an issue.
