### ISSUE TITLE
Permission hierarchy

### ISSUE THREAD

**Issue by sedubois** [graphcool/console#239]
Supposedly, someone who's authenticated should be able to do everything a guest can do? The dashboard doesn't reflect this right now, e.g guest is able to delete whereas authenticated can't.

![untitled](https://cloud.githubusercontent.com/assets/4217871/19019438/42012bc6-8891-11e6-86c6-7025fff8953e.png)

**Comment by schickling** [comment]
Will be replaced by new permissions structure landing in M7.
