### ISSUE TITLE
Can't remove role from Authenticated permission

### ISSUE THREAD

**Issue by sedubois** [graphcool/console#242]
E.g on User model > Fieldname email > Permissions, when there already exists an Authenticated permission with ADMIN role. When clicking the delete cross next to "Limit to ADMIN" then pressing "Save", then collapsing and re-opening the Permissions, then in the Authenticated permission the ADMIN role reappears.

**Comment by schickling** [comment]
Will be replaced by new permissions structure landing in M7.
