### ISSUE TITLE
Structure table column misalignment

### ISSUE THREAD

**Issue by sedubois** [graphcool/console#245]
E.g here, `Fieldname` `contentType` is too long leading to constraints and permissions labels to be misaligned for that row.

<img width="921" alt="screen shot 2016-10-03 at 14 20 23" src="https://cloud.githubusercontent.com/assets/4217871/19035811/9d4b39de-8974-11e6-9803-3dab63466417.png">

**Comment by timsuchanek** [comment]
Fixed with ellipsis, however, the right solution would be to do calculation of the fieldName length
