### ISSUE TITLE
hovering on system fields shouldn't make the type invisible

### ISSUE THREAD

**Issue by brene** [graphcool/console#264]
mouseOver:
![image](https://cloud.githubusercontent.com/assets/4989523/19283170/3b2cb9a2-8ff1-11e6-8bd3-4226e3b06125.png)

mouseNotOver:
![image](https://cloud.githubusercontent.com/assets/4989523/19283190/4913c6f0-8ff1-11e6-8d86-3db70ace2816.png)

**Comment by timsuchanek** [comment]
Already Done :)
