### ISSUE TITLE
Every second row should be colored differently

### ISSUE THREAD

**Issue by brene** [graphcool/console#265]
![image](https://cloud.githubusercontent.com/assets/4989523/19283238/67a5cf0a-8ff1-11e6-8c90-95e5f0de9ff5.png)

**Comment by schickling** [comment]
@julianbauer what's your opinion on this?

**Comment by julianbauer** [comment]
I don't think it's necessary, the focus highlight is sufficient. But let's keep an eye on this!

**Comment by schickling** [comment]
What's your reasoning behind this @brene?

**Comment by brene** [comment]
I used graphcool on a friend's ultra wide monitor. And it was kind of difficult to look at the data when you have a lot of columns and very large/wide window.

[!image](https://images-na.ssl-images-amazon.com/images/I/51HmwWdc76L.jpg)

**Comment by schickling** [comment]
Let's keep this issue open and see if it's a problem for other people as well.
