### ISSUE TITLE
Rewrite import feature

### ISSUE THREAD

**Issue by brene** [graphcool/console#286]
![image](https://cloud.githubusercontent.com/assets/4989523/19512944/88ea831a-95ee-11e6-9dd5-1a8bb37a9a18.png)
I thought there was a new feature that allows me to download an `.csv` of my app but then I realized it was the import feature. I think the arrow should point upwards, since it's "uploading" data.

**Comment by Pedro-vk** [comment]
I thank the same. I think that could be a good solution the addition of tooltips or similar.

**Comment by schickling** [comment]
@julianbauer what are your thoughts on this?

**Comment by sorenbs** [comment]
We need to make this feature more robust and properly document it. I suggest that we hide the button for now and reenable it when we have the capacity to do it right.

**Comment by timsuchanek** [comment]
Ok, good idea, I'll remove the icon first, later we should come back to this

**Comment by brene** [comment]
I guess I can close this as I can't find the import feature anymore.
