### ISSUE TITLE
Auth0 "enable" button is below the fold and the modal is not scrollable

### ISSUE THREAD

**Issue by cartogram** [graphcool/console#290]
I am using a 13inch Macbook 2015.

The three fields required to configure Auth0 push the modal controls off the screen and I can't scroll to them. Perhaps position them absolutely to the bottom of the modal, set the height of the other div above it using `calc(100% - $height-of-modal-contols)`, and set the overflow to scroll.

**Comment by schickling** [comment]
Closing this issue as it's an duplicate of #257
