### ISSUE TITLE
Unique constraint is reset when editing field properties

### ISSUE THREAD

**Issue by sedubois** [graphcool/console#292]
E.g I have a `User` model with `slug` field, I set the field to be unique, then click the edit button (pencil button), which opens a popup, then simply click "save" without any other action: it will reset the unique constraint.

**Comment by schickling** [comment]
Thanks for reporting this. We'll look into fixing this soon!

**Comment by sorenbs** [comment]
It seems like the dashboard always send `isUnique: false` even when the field is unique.
