### ISSUE TITLE
Relation creation UX improvements

### ISSUE THREAD

**Issue by christrotter89** [graphcool/console#298]
**Modal size**
The modal is taking up the entire height of the window despite this not being needed. A max-height should be applied to this window. [To be linked to other issue regarding modal sizes in general.]

**Validation**
Small UX point. When creating a relation name, it would be useful if the current information icon is green or red depending on whether current input is valid. When clicking create, if validation fails a label should popup from the information icon with the error prompt.

Just a thought but perhaps you could auto-enforce the first character to be capitalised? Will assist with validation and user journey.

[Screenshot](https://www.evernote.com/shard/s504/sh/3f971366-7041-4d13-a59e-8272d3099972/b2073f954b1d6539b7b83f0f89ddfe58)

**Comment by schickling** [comment]
Probably related to #255

**Comment by timsuchanek** [comment]
Already implemented :)
