### ISSUE TITLE
Field popup: List fields cannot have a default/migration value

### ISSUE THREAD

**Issue by christrotter89** [graphcool/console#301]
- [x] When creating a list, the placeholder name is 'Fieldname', but capitalising the first character of a field is invalid. Should change the placeholder to 'fieldname' to assist users.
- [ ] It appears not possible to add a default value to a list field or to have a migration value. Is this intended?

**Comment by timsuchanek** [comment]
Good pointer, we will redo the field popup soon, then this will be taken into account

**Comment by schickling** [comment]
I've tested the backend and it works. Handing it over to @timsuchanek.
