### ISSUE TITLE
Action page UX

### ISSUE THREAD

**Issue by christrotter89** [graphcool/console#303]
On the action page there is a _create action_ button on the top left, but for the most part the entire screen is blank. I think this is a good opportunity to show create action use cases or give a brief overview of what they are. Johannes previously demoed some cool possibilities of this to me.

**Comment by timsuchanek** [comment]
@julianbauer What are your thoughts on this?

**Comment by julianbauer** [comment]
Generally, we plan to add "empty" states to pages that show you a blank screen when you visit them the first time, in the near future – like actions or relations. What you suggested fits in there really well, accompanied by a big _create action_ Button.
