### ISSUE TITLE
No reactive behaviour for other side of new relation within the same model

### ISSUE THREAD

**Issue by christrotter89** [graphcool/console#304]
When creating a relation between one node and another node within the same model, the source field updates but the destination relation field does not reactively update with the relationship. Likely due to only the current row being re-rendered instead of the entire table?

**Comment by sorenbs** [comment]
@timsuchanek This is fixed in the backend. So now we can implement the refresh of other row in the frontend.

**Comment by timsuchanek** [comment]
@sorenbs Awesome! Will do that after my trip to the backend :)

**Comment by sorenbs** [comment]
🙌
