### ISSUE TITLE
Dialogs stacking on top of each others

### ISSUE THREAD

**Issue by GHermet** [graphcool/console#308]
![](http://i.giphy.com/PbwWRhFcnanWU.gif)

**Comment by schickling** [comment]
@timsuchanek this seems to be related how the popups are initialized in the sidebar. Please take a look.

**Comment by schickling** [comment]
- [ ] New model popup
- [ ] Endpoint popup

**Comment by timsuchanek** [comment]
Fixed in ab3665db1d65e8e2e78a2c8dab261c5d02e03965
