### ISSUE TITLE
Changing field to required yields internal server error

### ISSUE THREAD

**Issue by sedubois** [graphcool/console#310]
(at least) when a column has null values, changing the field to required but leaving the migration value empty leads to internal server error.

<img width="937" alt="screen shot 2016-10-27 at 17 11 08" src="https://cloud.githubusercontent.com/assets/4217871/19770561/612090c4-9c68-11e6-94ab-fcac666c889a.png">

**Comment by sorenbs** [comment]
Thanks for reporting this. I am looking into this issue asap.

**Comment by sorenbs** [comment]
Ok, I believe this is an issue specific to your project. Could you try one more time to make the field required?

**Comment by sedubois** [comment]
Same thing. However I don't observe https://github.com/graphcool/console/issues/309 any more.

**Comment by sedubois** [comment]
Actually, it yields the error even if there are no `null` values in the column.

**Comment by sedubois** [comment]
And even if I provide a migration value.

**Comment by sorenbs** [comment]
@sedubois I have identified the issue. I'll let you know when a fix has been deployed.

**Comment by sorenbs** [comment]
The internal server error should be fixed now. Please let me know if this works for you.

Please be aware that currently changing a field will remove its unique constraint as you reported in https://github.com/graphcool/console/issues/292. For now you can simply add the unique constraint again.

**Comment by schickling** [comment]
#292 has been solved as well. Thanks for brining this up!

**Comment by sedubois** [comment]
yes, works 👍 thanks @sorenbs
