### ISSUE TITLE
Empty models directly enter into add mode (bug?)

### ISSUE THREAD

**Issue by brene** [graphcool/console#322]
When I've never used Graph Cool before I'd have no idea that I should enter something into the row (but having said that, most people went through the tutorial). In the "File" model, it's super annoying since I have to click "No I would not like to save the changes" every time when accidentally go to the Browser view.

**Comment by schickling** [comment]
What do you think about this @julianbauer? I think @timsuchanek implemented this feature for a specific reason?

**Comment by timsuchanek** [comment]
This will be fixed by #327
