### ISSUE TITLE
Multiple places where "Endpoint", "Docs" and "Account" can be accessed

### ISSUE THREAD

**Issue by brene** [graphcool/console#326]
I can access these things here:
![image](https://cloud.githubusercontent.com/assets/4989523/19782141/d57e1756-9c8c-11e6-9c5f-e511695cc19c.png)
and
![image](https://cloud.githubusercontent.com/assets/4989523/19782145/db04073a-9c8c-11e6-9281-93085b0980ca.png)

and for accounts:
![image](https://cloud.githubusercontent.com/assets/4989523/19782162/ebaef68a-9c8c-11e6-8a0f-5941b374f7eb.png)
and 
![image](https://cloud.githubusercontent.com/assets/4989523/19782164/f0368cfe-9c8c-11e6-920d-2bfdc479d127.png)
would be great to standardize this :D

**Comment by schickling** [comment]
Thanks for bringing this up. This will be resolved in the next release!
