### ISSUE TITLE
File model: disallow create from databrowser

### ISSUE THREAD

**Issue by sorenbs** [graphcool/console#327]
When adding a File node in the databrowser the api returns an error. Either

1) Disallow adding a File node in the databrowser
2) Implement special handling for file nodes that use the file endpoint

**Comment by timsuchanek** [comment]
@sorenbs Some for the User model, we should show a proper error message, maybe a link to the docs?

**Comment by schickling** [comment]
Yup, good idea! @julianbauer how would that look like?
