### ISSUE TITLE
Implement new fields list

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/console#338]

**Comment by GHermet** [comment]
<img width="712" alt="screen shot 2016-11-02 at 09 45 05" src="https://cloud.githubusercontent.com/assets/11071350/19922076/42d15842-a0e1-11e6-944f-be590513a196.png">

**Comment by GHermet** [comment]
<img width="1280" alt="screen shot 2016-11-02 at 16 17 37" src="https://cloud.githubusercontent.com/assets/11071350/19935236/93e1e660-a119-11e6-909c-19a75be56f02.png">

**Comment by GHermet** [comment]
<img width="1280" alt="screen shot 2016-11-02 at 18 31 46" src="https://cloud.githubusercontent.com/assets/11071350/19939866/eb2e5fb4-a12a-11e6-9f85-a06f45e85ca9.png">

**Comment by GHermet** [comment]
<img width="1280" alt="screen shot 2016-11-03 at 14 24 41" src="https://cloud.githubusercontent.com/assets/11071350/19967603/53dc8cc4-a1d1-11e6-897a-e1bef5469d98.png">
