### ISSUE TITLE
Add explanation why it's not possible to create a File/User node via the databrowser

### ISSUE THREAD

**Issue by schickling** [graphcool/console#344]
![](https://i.gyazo.com/48a24a68696b38b112b5eb18935e3f85.gif)

**Comment by hvdklauw** [comment]
Indeed, why?

**Comment by timsuchanek** [comment]
Because it's a system model, which needs special input that currently can't be added via the databrowser.
At the moment it's only possible to add those nodes (File and User) with the api.
A note has been added in 	eb84d1f
