### ISSUE TITLE
Misaligned elements

### ISSUE THREAD

**Issue by marktani** [graphcool/console#350]
![misaligned-2](https://cloud.githubusercontent.com/assets/1780597/19835699/99a6466e-9e8e-11e6-9066-7cf0409f1c79.png)
![misaligned-1](https://cloud.githubusercontent.com/assets/1780597/19835700/99ca0d1a-9e8e-11e6-9c4b-12129b18bdb4.png)

in the schema editor, the Create Field button is misaligned.
in the databrowser, the three buttons (Search, Upload, Refresh) are misaligned.

**Comment by timsuchanek** [comment]
this is the design :D
