### ISSUE TITLE
Onboarding: Second field does not have tether telling you what it should be called

### ISSUE THREAD

**Issue by sorenbs** [graphcool/console#357]
![image](https://cloud.githubusercontent.com/assets/281337/19838848/e632df3a-9ed7-11e6-8847-6bc3af956f2d.png)

**Comment by timsuchanek** [comment]
Yes, isn't that intentional @schickling @brene ?

**Comment by sorenbs** [comment]
I had to close the popup to figure out what to call it. Scary! 🙀

**Comment by schickling** [comment]
@julianbauer what do you think about this?

**Comment by brene** [comment]
We use to have a Tether there.

**Comment by timsuchanek** [comment]
Until other people find it odd, too, we will leave it like this, as the idea of it was to have the second run less guided
