### ISSUE TITLE
Onboarding: Copy example value is confusing.

### ISSUE THREAD

**Issue by sorenbs** [graphcool/console#359]
Testing in safari

1) At first it didn't work. I clicked the button many times and nothing happened. Tried to paste into the cell, nothing happened. A few tries later it did work.

I thought the button would just copy the example into the cell directly. 

Maybe we can just write "Use default value" and paste it directly to the cell?

2) Enter description tether points to wrong cell

![image](https://cloud.githubusercontent.com/assets/281337/19838899/bd8fdd66-9ed8-11e6-8db8-0a66ba21764c.png)

**Comment by marktani** [comment]
2) confirmed on Linux/Chrome

**Comment by schickling** [comment]
@julianbauer what do you think?

**Comment by timsuchanek** [comment]
We will implement "use example value" instead

**Comment by timsuchanek** [comment]
Implemented by ff871212e7a1544d9cb34212037920729084d2b9
