### ISSUE TITLE
Onboarding: GraphiQL introduction is overwhelming

### ISSUE THREAD

**Issue by sorenbs** [graphcool/console#364]
It's not clear that you have to scroll down.

It is difficult to focus on the content of the popup because the screen is too busy.

![image](https://cloud.githubusercontent.com/assets/281337/19839016/efa994f2-9eda-11e6-85e5-f861d9d82d39.png)

**Comment by timsuchanek** [comment]
I totally agree, that was my impression, too.
@julianbauer How could we make this less complex?
