### ISSUE TITLE
Onboarding for Relations: Better UX if Field already exists

### ISSUE THREAD

**Issue by ThisIsMissEm** [graphcool/console#388]
When adding a relation, if that field already exists, then I should be asked one of the following:
- Do I wish to merge / migrate the data (requires treating the existing data as ID values)
- Or, do I wish to drop the field and create a relation in it's place.

I initially missed the part about relations (it's not in onboarding), so I first created a field on my Post model called "user", but then found I couldn't select GraphQLID! type, so discovered relations, but then couldn't create a relation because that user field already existed (despite being empty)

**Comment by timsuchanek** [comment]
Good point! I see how blind we get for those details when we're using the console the whole day :)
I think going for a better explanation in the onboarding would be the best solution, as the case for such a migration shouldn't occur.

**Comment by timsuchanek** [comment]
Solution implemented in f6db6a035bbf9301560ce94795f19378c08e2198
If views are empty, eg. when there are no relations, we now show some intro text and a link to the docs.
