### ISSUE TITLE
Relations: Customisable Mutations

### ISSUE THREAD

**Issue by ThisIsMissEm** [graphcool/console#389]
Presently when I create a relation, I automatically get two mutations created. This is both good and bad; From an administration point of view, it makes sense that I'd have these mutations.

However, from a client's perspective, there's generally a case that the client shouldn't be able to mutate the relation directly, e.g., you can only create a post with the user you're logged in as, and you can change the owner of a post.

I'm thinking just something with two checkboxes next to the mutations that it'd create.

**Comment by schickling** [comment]
This will be mostly addressed by our new permission system which we'll roll out over the next few weeks. It all comes down to how default permissions are created.

I agree in a live/production system you wouldn't want to have this security problem.

**Comment by ThisIsMissEm** [comment]
Cool, looking forward to it & seeing the updates soon

**Comment by timsuchanek** [comment]
Should be fixed with our new query permissions, which you can test in beta already :)
