### ISSUE TITLE
Relations: Ability to mark a relation as "required"

### ISSUE THREAD

**Issue by ThisIsMissEm** [graphcool/console#390]
Presently you can mark them as unique, but you can't enforce that they exist, which means you might create a Post that doesn't belong to a User, hence it'd never show up.

This issue proposes a checkbox to mark a relation as a required value.

**Comment by schickling** [comment]
Thanks for bringing this up. It's already on our roadmap here: https://github.com/graphcool/feature-requests/issues/12
