### ISSUE TITLE
Onboarding: Give descriptions to fields in pre-created schemas

### ISSUE THREAD

**Issue by ThisIsMissEm** [graphcool/console#391]
After you've finished onboarding, there's two Schema that are already created, File and User; However, these don't come with any descriptions on their fields. To me, this confused me and made me not entirely understand how to work with them / what to do with them.

**Comment by timsuchanek** [comment]
Very good point! I think we should extend the onboarding and explain what they're about.

**Comment by timsuchanek** [comment]
We will implement interfaces which we will explain much better. Until then, this issue is on hold

**Comment by timsuchanek** [comment]
Already fixed, in an empty File and User model we have an intro now
