### ISSUE TITLE
Onboarding: Make the download optional

### ISSUE THREAD

**Issue by ThisIsMissEm** [graphcool/console#392]
Currently when doing the onboarding, you can't exit it or feel like you've completed it, until you download the example applications and run them. This make it feel like my onboarding is incomplete, even though I may not right now wish to download & run a node.js/javascript application.

**Comment by timsuchanek** [comment]
Right, we should enable some other exit possibility, or even the possibility to come back to that last modal if the user wants. We will split the content of the last onboarding modal into multiple steps next week, then we can also think about a better solution for the exit from the onboarding

**Comment by schickling** [comment]
@julianbauer any idea on how to do this?
