### ISSUE TITLE
UX: Make sidebar collapsible

### ISSUE THREAD

**Issue by ThisIsMissEm** [graphcool/console#393]
Currently the sidebar occupies a decent amount of screen real-estate, particularly so in the Playground; It'd be nice if the sidebar could collapse out of the way (perhaps just to icons?)

**Comment by timsuchanek** [comment]
@julianbauer what are your thoughts on this?

**Comment by julianbauer** [comment]
That's exactly what we had in mind. I could imagine that you can just resize the width of the sidebar, and then it may snap to the width of the green logo box: We would have a col-resize cursor near the right edge of the sidebar, to make it "draggable" – even if it's not seamless, and just jumps between the two states expanded/collapsed, we don't need extra UI-Elements for it. What do you think?

**Comment by timsuchanek** [comment]
I think we first should look into this problem: https://github.com/graphcool/console/issues/302
That could already improve the UX a lot, as this is eg. how I see the dashboard on high resolution, where I think the sidebar is not a problem:
<img width="1678" alt="screen shot 2016-11-08 at 5 38 46 pm" src="https://cloud.githubusercontent.com/assets/1094804/20107834/4163c6ea-a5da-11e6-8c1f-61bc6970e73a.png">

**Comment by ThisIsMissEm** [comment]
what about using the logo to do it?

But having a << button would be really nice as well.

**Comment by timsuchanek** [comment]
onhold waiting for design
