### ISSUE TITLE
When adding a new model: Analytics is not defined

### ISSUE THREAD

**Issue by sorenbs** [graphcool/console#419]
When adding a new model I get this error, and the console does not switch to the new model:

> vendor.e216a0c….js:28 Uncaught ReferenceError: analytics is not defined

![image](https://cloud.githubusercontent.com/assets/281337/20261010/418c72da-aa5c-11e6-86d8-5985ea91f72e.png)

**Comment by marktani** [comment]
also happens in the playground when running `createUser` mutation
