### ISSUE TITLE
auth providers overlay confusing 

### ISSUE THREAD

**Issue by marktani** [graphcool/console#421]
![auth-providers-overlay](https://cloud.githubusercontent.com/assets/1780597/20266588/1932e4b6-aa77-11e6-83a8-0e7fc8cf5488.png)

if you have no nodes/fields for `User`, the information message seems to break the auth provider overlay.
I cannot click anything in the overlay.

**Comment by timsuchanek** [comment]
:D fixed already, fix will be deployed in minutes
