### ISSUE TITLE
Relation fields on models aren't included in permission model

### ISSUE THREAD

**Issue by emolr** [graphcool/console#427]
If a Model have a relation field eg. Tags[Tag] then requesting the data as anyone but ADMIN will give error: `Code 3008: InsufficientPermissions`.

Maybe adding relation fields to the permission manager would fix this? 
A work-around atm is to add the whole model to a permission.

**Comment by sorenbs** [comment]
Thanks for digging in to this Emil!

A fix will be available in ~1 hour
