### ISSUE TITLE
Creating new user (already registred) with Auth0 idToken returns 3010 instead of 3023

### ISSUE THREAD

**Issue by emolr** [graphcool/console#436]
A working solution 2 weeks ago stopped working suddenly. 
I'm using auth0 custom implementation. 

Logging in with auth0 always tries to create new user, but catches error if userAlreadyExist, and then sign in using the idToken instead. 

Now error `Code 3023: CannotSignUpUserWithCredentialsExist` is not returned, but` Code 3010: UniqueConstraintViolation`is returned instead.

Is this an error or an intended change?

It's an easy fix, but error code 3023 made more sense to react on than 3010 :)

**Comment by schickling** [comment]
@sorenbs will fix this asap. We'll release an announcement around Auth Providers shortly.

**Comment by schickling** [comment]
This is fixed now @emolr. Please re-open if you still run into problems with this.
