### ISSUE TITLE
Special Characters within STRING field get replaced or erased

### ISSUE THREAD

**Issue by herrhelms** [graphcool/console#437]
There seems to be a limitation/filter for certain special characters (ASCII/UTF-8) within a `String` field. Some work others get erased or replaced with question marks `?`.  This appears to be happening to some but not all non-letter symbols. Is this a known bug or a feature?

I understand this in regards to code injection. Probably a good idea to do some filtering and escape quotation marks, brackets, parenthesis, etc. 

Example: Yen symbol `¥` works while Thai Bath symbol `฿` doesn't. - it's difficult to see any pattern.

**Comment by sorenbs** [comment]
Thanks for reporting this @herrhelms 

This is an issue with the way we parse incoming text. I'll update this issue when we have deployed a fix.

**Comment by schickling** [comment]
Hey @herrhelms! Quick update: It should be now working for your provided example. Can you please confirm?

**Comment by herrhelms** [comment]
I just randomly added a couple of special chars - works like a charm! Thanks

**Comment by schickling** [comment]
We keep this open until a few last problems with some special emojis are fixed. ⛑

**Comment by herrhelms** [comment]
Good thinking - I just tried emoji's too, but without luck. Good to know you're on it... 🎉

**Comment by schickling** [comment]
Quick update: This is blocked by https://github.com/akka/akka-http/issues/564

**Comment by timsuchanek** [comment]
Fixed
