### ISSUE TITLE
No default permission for new models/projects

### ISSUE THREAD

**Issue by brene** [graphcool/console#442]
![image](https://cloud.githubusercontent.com/assets/4989523/20455874/a5522284-ae66-11e6-9d77-1c0b87136b6b.png)
I just created a new project, I wish that the permission fields would be prepopulated. Otherwise, I wouldn't understand what the "default" permission is.

**Comment by schickling** [comment]
Thanks for reporting this. @sorenbs is already on it.

**Comment by timsuchanek** [comment]
Already fixed.

**Comment by sorenbs** [comment]
This is only fixed for new models. Currently, when you create a new project the Field and User model does not have the default permissions.

**Comment by sorenbs** [comment]
Fixed in backend
