### ISSUE TITLE
Increase contrast of circle in schema / data browser

### ISSUE THREAD

**Issue by ThisIsMissEm** [graphcool/console#457]
I'd actually been switching to the playground to manually delete records, as I didn't know I could select rows from the schema / data browser. I've only just noticed the little circle next to the rows after about 6 hours of usage of graph.cool

This may be because I'm normally coding with Flux on, which changes how my screen displays colours (to help your eyesight at night).

**Comment by brene** [comment]
I think generally, the UI is a little bit "washed out". The shades of gray (no pun intended) are too close to each other.

**Comment by timsuchanek** [comment]
Thats a very good point! Our first solution will be to have the points fixed to the left side, if this is still an issue then, we can also change the shade of grey.
This will be done in #37

**Comment by ThisIsMissEm** [comment]
Not sure what you mean be fixed points; but regardless, that combination of grey on grey is too low in contrast. 

I thought the most obvious fix would be to place it on a white background, but even then it's still too hard to see:

![screen shot 2016-11-23 at 3 03 25 pm](https://cloud.githubusercontent.com/assets/30827/20564559/102941bc-b18e-11e6-9252-a610a484a785.png)

At a colour of 0.15 alpha rather than 0.05, it's definitely more visible — also, I'm not sure I really want to ask re the CSS there, it looks very strange.

![screen shot 2016-11-23 at 3 06 39 pm](https://cloud.githubusercontent.com/assets/30827/20564668/8f0d3574-b18e-11e6-9b2a-7ccc779eedeb.png)

**Comment by ThisIsMissEm** [comment]
but even with the last change there, I'd say it's still too low-contrast (I was trying to keep within your design colours)

**Comment by timsuchanek** [comment]
@julianbauer what are your thoughts on this?

**Comment by timsuchanek** [comment]
Fixed
