### ISSUE TITLE
Settings icon next to Model Name confusing

### ISSUE THREAD

**Issue by brene** [graphcool/console#459]
![image](https://cloud.githubusercontent.com/assets/4989523/20551341/9cf54da6-b13f-11e6-887b-8e78b5a47d5c.png)
I think "settings icon" is a little bit weird. People could assume, it's a schema editor. I would expect a "pen", since the only functionality is to rename the model.

**Comment by timsuchanek** [comment]
@julianbauer Thoughts on this?

**Comment by brene** [comment]
I think we used to have a pen icon there, didn't we?
