### ISSUE TITLE
History tab not closable when no history

### ISSUE THREAD

**Issue by brene** [graphcool/console#461]
![image](https://cloud.githubusercontent.com/assets/4989523/20551461/dbdfd95e-b140-11e6-895c-703464e7f149.png)
If there is no history, no matter how often I click on "close", the tab just doesn't want to close.

**Comment by ThisIsMissEm** [comment]
I also get the history sticking around after clicking on an item in it; I suspect this may be related?

**Comment by brene** [comment]
When I was working on the dashboard a few months ago, I actually fixed this bug. So I'm kind of surprised it's back. So maybe @schickling it'll help to look at my old commits
