### ISSUE TITLE
Refreshing records after deletion results in incorrect sidebar count

### ISSUE THREAD

**Issue by ThisIsMissEm** [graphcool/console#464]
![screen shot 2016-11-23 at 6 40 22 am](https://cloud.githubusercontent.com/assets/30827/20552114/bcaad924-b147-11e6-9d51-d8d0ee368bba.png)

*Steps to Reproduce*

1. Create a new project
2. Create a new model, it doesn't matter on fields
3. Add some rows to it
4. Reload
5. Delete all the rows by selecting them and pressing "delete"
6. Press "refresh / reload" model rows

Result is as above, count should actually be 0

**Comment by timsuchanek** [comment]
it now flickers a littlebit after deleting, but that's due to the hard connection between relay & redux. with relay 2 this should get easier.
