### ISSUE TITLE
Implement delete Permission

### ISSUE THREAD

**Issue by emolr** [graphcool/console#465]
Permissions kind of live it's own life atm. 

I have a Post model which had `createNode` for authenticated users, i then added a new field `published: Boolean`, and then couldn't create a new post. 

I looked in the `permission` tab in console and `createNode` had disappeared from  the Post section. 
I added it again, but i can't delete former permissions, so now it looks like this:
<img width="1385" alt="screen shot 2016-11-24 at 10 45 45" src="https://cloud.githubusercontent.com/assets/2789549/20582299/fec2a3d6-b233-11e6-8a73-4dd107a293f4.png">

And i can't delete the ones i toggled off.

All the best

**Comment by schickling** [comment]
Seems like this is a regression bug. @timsuchanek is looking into it.
