### ISSUE TITLE
Link in the docs doesn't work

### ISSUE THREAD

**Issue by kitze** [graphcool/console#469]
This link in the docs doesn't work: https://jumpshare.com/v/gss6tc8nBxCZjFLmnuaG

The href is:
https://graph.cool/docs/reference/simple-api/(../platform/authentication)

**Comment by marktani** [comment]
Thanks for reporting this. I fixed the links in the document. I created a new issue in the docs repository to check other links: https://github.com/graphcool/docs/issues/48
