### ISSUE TITLE
Relation Description not visible in Model View

### ISSUE THREAD

**Issue by Deepakkothandan** [graphcool/console#475]
When creating a relationship between  models,, we provide a description text for the relationship. But this description is not visible in the edit schema view, even after saving the changes.
![image](https://cloud.githubusercontent.com/assets/7385180/20860934/012d7248-b984-11e6-9130-7b3dc409fc6a.png)

![image](https://cloud.githubusercontent.com/assets/7385180/20860935/0f679e74-b984-11e6-9c1a-bc2a8215604a.png)

**Comment by marktani** [comment]
Hey, I cannot reproduce the error, do you see error logs in the DevTools of your browser?

**Comment by Deepakkothandan** [comment]
@marktani Thank you for looking in to this. Posting another screenshot with the errors. You can notice that the description for field appears, but the description for relationship does not appear.

![image](https://cloud.githubusercontent.com/assets/7385180/20861089/a58af6aa-b987-11e6-8670-876e7e8a47a9.png)

**Comment by marktani** [comment]
Ah right. I can confirm this problem. In the relation popup itself the description is shown, but in the Schema view it isn't. Thanks for the report! :+1:
