### ISSUE TITLE
Show warning popup when trying to remove a field which is generated by a relation

### ISSUE THREAD

**Issue by marktani** [graphcool/console#477]
The following steps were executed, at some point some inconsistencies were introduced. To really find the problem we have to reproduce and check after every step:

* create `Destination` model
* create `UserDestination` one-one relation, with fields `user` and `destination`
* in the user schema view, click the remove icon on the `destination` field in the model view (that might have resulted in the inconsistency)
* in the user schema view, create a new String field called `destination`
* any action in the console results in internal server error, even certain queries/mutations to the API results in internal server error.

this could be resolved by logging out and logging back in. might have been some schema caching problem or a dangling relation

**Comment by marktani** [comment]
Maybe related to #467 ?

**Comment by sorenbs** [comment]
Removing fields that are part of a relation should not be possible. I'l create a separate task to fix this in the system api. The console should not display ui to remove fields in a relation. I have updated title to reflect this.
