### ISSUE TITLE
System models are in data browser mode by default

### ISSUE THREAD

**Issue by marktani** [graphcool/console#479]
<img width="333" alt="bildschirmfoto 2016-12-05 um 17 35 42" src="https://cloud.githubusercontent.com/assets/1780597/20893323/afac3b36-bb11-11e6-8484-806deba06fc0.png">

reported on Chrome 54. I could not reproduce this issue.

Thanks to @KApo09 for the report.

**Comment by KApo09** [comment]
Just understood why I don't see these fields:
The system models are (in my case) by default not in the "EDIT SCHEMA" mode. When project is new I would recommend to keep it it consistent and leave als system models in this mode until they are populated ... 
<img width="191" alt="bildschirmfoto 2016-12-05 um 17 52 03" src="https://cloud.githubusercontent.com/assets/3482749/20893986/171fe1b2-bb14-11e6-8e29-be3fc376e1cd.png">

**Comment by marktani** [comment]
The way it works is that models that already have nodes are in schema mode. Models without nodes are in data browser mode. Do you already have users (or files) in your project?

**Comment by KApo09** [comment]
No.

**Comment by timsuchanek** [comment]
This is a good point, currently it's inconsistent.
In the near future, we will introduce interfaces and not have predefined system models.
Until then, the issue is on hold.
