### ISSUE TITLE
Permission Selection effect broken

### ISSUE THREAD

**Issue by brene** [graphcool/console#486]
![image](https://cloud.githubusercontent.com/assets/4989523/20920492/6d627c92-bba0-11e6-8022-3cb754a78e97.png)
I don't understand why the blue thing is on the far left

**Comment by timsuchanek** [comment]
@julianbauer how could we improve this?

**Comment by timsuchanek** [comment]
It's meant like that. The idea is "nothing is selected right now"
Closing it right now, if it comes up again, we can reopen it
