### ISSUE TITLE
Permission overview icons misleading

### ISSUE THREAD

**Issue by brene** [graphcool/console#487]
![image](https://cloud.githubusercontent.com/assets/4989523/20920525/91a8e94c-bba0-11e6-8db9-ca853324da1a.png)
the small rounded icons on top look like they are columns descriptors for the table below. I was wondering for 10 minutes why the "columns" are empty. Until I realized that the icons are just a high-level overview. Maybe align the icons to the left, so it doesn't look confusing?

**Comment by timsuchanek** [comment]
@julianbauer What do you think?
