### ISSUE TITLE
Filter by null value

### ISSUE THREAD

**Issue by sorenbs** [graphcool/console#494]
It should be possible to filter for null values:

```
{ allItems(filter: {deletedAt:null}) { id } }
```

**Comment by jcheroske** [comment]
What happened with this? I'm trying to do almost this exact thing and have hit an error. Is there a workaround?

**Comment by sorenbs** [comment]
Hi @jcheroske 

This is caused by a limitation in an old version of the Apollo client. Could you try to update to the latest version?

Alternatively you can work around it by using variables in the client as suggested by the error message.

Graphcool does support this kind of query. You can verify this by running it in the Console Playground :-)
