### ISSUE TITLE
DataBrowser: blur json field -> JSON.stringify's each time

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/console#528]
![image](https://cloud.githubusercontent.com/assets/1094804/21688490/56c2926c-d36d-11e6-9506-b375e0498b06.png)

**Comment by marktani** [comment]
this bug is still apparent

**Comment by mypark** [comment]
yeah it happens when the field is empty and you focus away - then focus away again.  It doesn't seem to happen when there's a value in the field already.
