### ISSUE TITLE
Problems with assigning enum fields

### ISSUE THREAD

**Issue by marktani** [graphcool/console#537]
Sometimes assigning enums to a enum list field doesn't work
![tag-enum-list](https://cloud.githubusercontent.com/assets/1780597/21743740/b2ba078e-d508-11e6-956b-d9a37d6da252.png)

**Comment by marktani** [comment]
I think the errors in the screenshot are unrelated. If I try to set an enum now, there is no call to the API in the network tab.

**Comment by marktani** [comment]
This happens when I click on the remove button in the enum dialog
![remove-enum-button](https://cloud.githubusercontent.com/assets/1780597/21743793/ef76dff2-d509-11e6-9db6-8fa132041843.png)

**Comment by timsuchanek** [comment]
Can't reproduce. Reopen when that is not the case anymore
