### ISSUE TITLE
Improve displaying system fields in data browser

### ISSUE THREAD

**Issue by julianbauer** [graphcool/console#541]
System fields like `createdAt` or `updatedAt` need a lot of space right now, which can make the interaction with the databrowser hard, even if you have a medium-sized screen (the first editable column is around 1000px from the left).

Suggestion: 

1) Make the columns only as wide as they have to be (based on the column headline for example)
2) Move them to the end of the list, so that the focus is on the actual editable items
3) Consider hiding those fields in create mode

**Comment by timsuchanek** [comment]
First solution: fixed size for id, createdAt, updatedAt
