### ISSUE TITLE
Improve error message for invalid project names

### ISSUE THREAD

**Issue by marktani** [graphcool/console#544]
Error message demands capital letters even for invalid project names like this: `Project-Name` where `-` is invalid.

**Comment by sorenbs** [comment]
![image](https://cloud.githubusercontent.com/assets/281337/21855344/79485988-d81e-11e6-8bea-3d2142baea61.png)

This error message is displayed by the frontend. We should create a proper ui and update the error message. This is the name constraint: "^[A-Z][a-zA-Z0-9 ]*$"

**Comment by marktani** [comment]
When cloning a project, this popup is not in play at all.

**Comment by sorenbs** [comment]
It's still ugly :-D

![image](https://cloud.githubusercontent.com/assets/281337/21855481/0202829e-d81f-11e6-8cbb-b1a45560b43b.png)


The clone project error is also created by the Console

**Comment by marktani** [comment]
> A project name has to start with a capital letter and may only contain alphanumeric letters and spaces.
