### ISSUE TITLE
Selecting related item in data editor displays error

### ISSUE THREAD

**Issue by mypark** [graphcool/console#548]
Selecting related item in the data shows this error and an empty field

`JSON object expected spray json deserialization`

However - it does look like the data is set correctly and persisted.

Steps to reproduce

1. create a post with a relation "author" to user table
2. select a user in the author column in the data table view for an existing row

**Comment by mypark** [comment]
![screen shot 2017-01-11 at 2 49 19 pm](https://cloud.githubusercontent.com/assets/470164/21863893/41325a78-d80d-11e6-8817-1970307fcdb2.png)

**Comment by sorenbs** [comment]
Thanks for reporting this @mypark! The issue originated in the Algolia integration that wasn't set up to sync json fields. This is now fixed :-)
