### ISSUE TITLE
Improve error message for skip < 0

### ISSUE THREAD

**Issue by ivan133** [graphcool/console#550]
I've mistakenly sent query with skip < 0

`    query allGuests {
        allGuests(first: 10, skip: -10, orderBy: phone_ASC) {
          id
        }
    }
`
I got response 

>    "message": "Whoops. Looks like an internal server error. Please contact us in Slack (https://slack.graph.cool) and send us your Request ID: cixuft6hz9ypz0177409qmk5a",
  
I think it's a bit confusing and it should be improved.

**Comment by sorenbs** [comment]
Thanks for raising this issue Ivan. We now return a proper error message when this happens :-)
