### ISSUE TITLE
enabled Auth providers breaks auth providers in cloned project 

### ISSUE THREAD

**Issue by marktani** [graphcool/console#551]
> I'm having an issue with a project clone I did. I had linked Auth0 to the project I cloned, but it seems like it didn't work properly for the clone cause now it won't recognize the `createUser()` mutation. When I go into my User model to Configure Auth Providers, it says Auth0 isn't active, so I click to activate it, but then the system tells me there's already a `auth0UserId` field (which there is). So I'm stuck and can't activate Auth0 and I can't delete the User model to rebuild it.

**Comment by sorenbs** [comment]
Fixed
