### ISSUE TITLE
Field Popup: Default Value Not Accepted for Enum Value

### ISSUE THREAD

**Issue by philcockfield** [graphcool/console#556]
With a field with the following values the `Default Value` textbox will not accept values.  When typing on the keyboard nothing appears in the texbox.

![image](https://cloud.githubusercontent.com/assets/185555/21959353/3f01d5f2-db29-11e6-8618-21f4a2a4eaed.png)

**Comment by timsuchanek** [comment]
Resolved in new popup :)
Will be deployed today
