### ISSUE TITLE
Cannot see my usage statistics

### ISSUE THREAD

**Issue by brene** [graphcool/console#56]
When I go to https://dashboard.graph.cool/{project}/account/usage it's just white. If I go there through the "Usage" tab in my "Account", it just doesn't load.

**Comment by sorenbs** [comment]
I'll look into this right away!

**Comment by sorenbs** [comment]
This feature is still in development :-)

We will hide the tab until it is fully ready. Thanks!

**Comment by schickling** [comment]
I'll keep this issue open until it's implemented 👍

**Comment by brene** [comment]
@sorenbs this issue is in this milestone. Do you think this can be implemented by the end of this week? Otherwise, I would push this onto next week

**Comment by sorenbs** [comment]
@brene Let's push it to next week

**Comment by timsuchanek** [comment]
Continuing in https://github.com/graphcool/feature-requests/issues/29
