### ISSUE TITLE
GraphiQL autocompletion for variables input prevents setting variables to null

### ISSUE THREAD

**Issue by marktani** [graphcool/console#568]
If you have a variable `name` and try to enter this in the variable input:

```
{
  "name": null
}
```

you cannot do that. once you start typing the letter `n` from `null`, it will be autocompleted with a different thing

**Comment by timsuchanek** [comment]
This is more a GraphiQL thing, but letting this open so we don't forget it

**Comment by marktani** [comment]
Seems to be fixed.
