### ISSUE TITLE
GraphiQL autocompletion for types variable parameters does not work 

### ISSUE THREAD

**Issue by marktani** [graphcool/console#569]
Consider this mutation:

```
mutation {
  createUser(...) {
    id
  }
}
```

Now introducing a variable, you can autocomplete after `mutation($variable:` (need to scroll to dozens of types) or you start typing but then there is no autocompletion anymore. 

The fastest way to find out the needed type for an object is to supply it a variable of type String for example and read the error message that tells the needed type...:

```
mutation($variable: String) {
  createUser(
    contactDetails: $variables # this shows an error in GraphiQL telling the correct type the variable expects
  )
}
```

**Comment by timsuchanek** [comment]
Same as #568: This is more a GraphiQL thing, but letting this open so we don't forget it

**Comment by marktani** [comment]
See https://github.com/graphql/graphiql/issues/389.
