### ISSUE TITLE
it is impossible to add another User node while logged in

### ISSUE THREAD

**Issue by cullan** [graphcool/console#578]
I am planning to make a page where admin users can create other user accounts manually instead of allowing open sign up.

I made a create node permission for the User model (authenticated) with this rule.

    {
      User(id:$userId) {
        roles(filter: {name: "admin"}) {
          id
        }
      }
    }

When I log in as a user with the admin role, I cannot create a user. I get the message `"It is not possible to create a user when you are already signed in."`

**Comment by sorenbs** [comment]
Thanks for raising this issue Cullan. This was an arbitrary rule we put in place at the very beginning and I don't think it makes sense any more. I have removed the rule. Please let me know if everything works as expected - there might be a few cases where we mix permissions between the current user and the newly created user. I'll add proper tests for all these cases in the near future, but if you run into anything, please let me know.

**Comment by cullan** [comment]
Thank you. I am able to create new users now as expected.
