### ISSUE TITLE
new relation popup background color cut off after scrolling

### ISSUE THREAD

**Issue by brene** [graphcool/console#595]
![image](https://cloud.githubusercontent.com/assets/4989523/22448543/fb18347a-e70e-11e6-8404-0a0289bf5ecf.png)
1. Create a relation
2. select enough options to make the page scrollable
3. 😱 realize that the background is cut off

**Comment by timsuchanek** [comment]
Will have new popup soon

**Comment by timsuchanek** [comment]
Resolved by the new relations popup
