### ISSUE TITLE
new relation popup title not visible after the popup becomes to large

### ISSUE THREAD

**Issue by brene** [graphcool/console#596]
![image](https://cloud.githubusercontent.com/assets/4989523/22448570/2694e5c6-e70f-11e6-9b71-bc55dff99346.png)
it is not possible to see "new relation" at the top of the popup anymore, once the popup is bigger than the screen.

**Comment by timsuchanek** [comment]
We will have a new relations popup soonish, (next 2-3 days)

**Comment by timsuchanek** [comment]
Resolved by new popup
