### ISSUE TITLE
default value tooltip placed at inconvenient location blocking direct user input

### ISSUE THREAD

**Issue by brene** [graphcool/console#600]
I wish the tooltip would open up to the top, since I just activated the checkbox on the left. 
![jan-30-2017 17-16-38](https://cloud.githubusercontent.com/assets/4989523/22448693/fc9fba60-e70f-11e6-8fb4-b01a8771afa4.gif)

**Comment by timsuchanek** [comment]
We will have also a new field popup this week :)

**Comment by timsuchanek** [comment]
Resolved by new popup
