### ISSUE TITLE
Cannot enter default value for int lists

### ISSUE THREAD

**Issue by brene** [graphcool/console#601]
![jan-30-2017 17-18-51](https://cloud.githubusercontent.com/assets/4989523/22448729/360e2a52-e710-11e6-8cdc-7c603e7b15ec.gif)
And the "create" button shouldn't light up if the value is not valid anyway :-)

**Comment by timsuchanek** [comment]
Will be fixed in new field popup this week

**Comment by timsuchanek** [comment]
Closing in favor of #301
