### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by marktani** [graphcool/console#610]
thanks to @ads1018 for the question

> I'm using apollo-client and graph.cool. When attempting to pass in the request headers to graph.cool via apollo's [`createNetworkInterface`](http://dev.apollodata.com/core/network.html#createNetworkInterface) method I'm throw an ssl error:

```
500
Internal Server Error.
Error: Network error: request to https://api.graph.cool/simple/v1/cixmkt2ul01q00122mksg82pn failed, reason: write EPROTO 140736952869824:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:769:
Error
    at new ApolloError (/Users/ads1018/Sites/next-apollo-example/node_modules/apollo-client/src/errors/ApolloError.js:29:23)
    at /Users/ads1018/Sites/next-apollo-example/node_modules/apollo-client/src/core/QueryManager.js:143:39
    at /Users/ads1018/Sites/next-apollo-example/node_modules/apollo-client/src/core/QueryManager.js:640:25
    at Array.forEach (native)
    at /Users/ads1018/Sites/next-apollo-example/node_modules/apollo-client/src/core/QueryManager.js:637:27
    at Array.forEach (native)
    at QueryManager.broadcastQueries (/Users/ads1018/Sites/next-apollo-example/node_modules/apollo-client/src/core/QueryManager.js:634:42)
    at QueryManager.broadcastNewStore (/Users/ads1018/Sites/next-apollo-example/node_modules/apollo-client/src/core/QueryManager.js:63:14)
    at /Users/ads1018/Sites/next-apollo-example/node_modules/apollo-client/src/ApolloClient.js:30:44
    at Object.dispatch (/Users/ads1018/Sites/next-apollo-example/node_modules/redux/lib/applyMiddleware.js:45:18)
```
> It seems like graph.cool doesn't like when I pass request headers for some reason. It works perfectly fine when I don't pass them. Could someone clarify this issue?

**Comment by ads1018** [comment]
Anyone else running into this issue? You can reproduce it with this example: 
https://github.com/zeit/next.js/tree/master/examples/with-apollo

Just pass headers to `createNetworkInterface` here: https://github.com/zeit/next.js/blob/master/examples/with-apollo/lib/initClient.js#L12

(Note: in that example I'm currently passing request headers to `ApolloClient` which is incorrect)

**Comment by marktani** [comment]
Hey Adam, I am not clear what you actually want to achieve. This is how you can add headers to your request: http://dev.apollodata.com/react/auth.html#Header

Looks like you are only passing cookies.

**Comment by marktani** [comment]
> (Note: in that example I'm currently passing request headers to ApolloClient which is incorrect)

Ah, I see. What kind of headers are you passing and what do you want to accomplish by passing these headers?

**Comment by ads1018** [comment]
When I serve my own graphql server I usually pass the headers for authentication and/or cookies. I don't necessarily need to for anything specific at the moment but I noticed the error in my Next + Apollo example I thought I should report it. Could you think of any instances where one might want to pass headers to graph.cool? If not, I guess it's not a critical bug.

**Comment by marktani** [comment]
The only header that you can set is for authorization: https://www.graph.cool/docs/faq/graphcool-session-user-goij0cooqu

Closing this, if you want to accomplish something specific with a header, please create a feature request here: https://github.com/graphcool/feature-requests
