### ISSUE TITLE
search is broken when model has list of strings

### ISSUE THREAD

**Issue by marktani** [graphcool/console#617]
Let's say I have `tags: [String]!` in my model `Model`, when I enter something in the search box it says 
> unknown field 'tags_contains' is not defined in the input type 'ModelFilter'. (line 4, column 149)

**Comment by frederickfogerty** [comment]
Hey @marktani @timsuchanek does this just affect the console, or Graph.cool as a whole? I can't `contains` to work in the Playground. Is `contains` documented anywhere

**Comment by marktani** [comment]
It's not documented because the actual API is not set in stone.

For string fields, `contains` is available, it matches nodes that contain the passed string in that field value.

There are no list filters for strings yet, but we are working on it: https://github.com/graphcool/feature-requests/issues/60

**Comment by frederickfogerty** [comment]
Thanks @marktani 🙌  Can't wait the list filters for string to be available 👍
