### ISSUE TITLE
Finetune Relations Popup

### ISSUE THREAD

**Issue by nikolasburk** [graphcool/console#628]
## Important

- [x] selected tab should be underlined @nikolasburk 
- [x] relation name is a bit higher than input field which makes the header move when switching between regular and editing state --> fix height for both @nikolasburk 
- [x] editing description changes height @nikolasburk 
- [x] info box on "Define Relation"-tab should have same style as info box on "Set Mutations"-tab @nikolasburk 
- [x] field name input not blurred when clicking above @nikolasburk  [demo](http://www.giphy.com/gifs/26xBIHe4pJMibyvQc)
- [x] editing field name changes size @nikolasburk 
- [x] Loading state when saving @nikolasburk 
- [ ] clicking outside of popup should just close it if there are no changes made @nikolasburk 
- [ ] deal properly with long field names (model selection box + whole popup grow) @julianbauer 
- [ ] triangular dropdown indicator on model selection box @nikolasburk 
- [ ] model boxes should be wide enough for mouse hover @nikolasburk [demo](http://www.giphy.com/gifs/26gskishs9L84PkME)
- [ ] adjust dropbox styling @nikolasburk 

## Optional

- [ ] popup should stay at same scroll position when switching tabs/resizing @timsuchanek 
- [ ] model shadow boxes should be animated when changing cardinality @nikolasburk

**Comment by marktani** [comment]
feedback: clicking outside the popup closes the popup in any state, even when there is a breaking change info box or unsaved changes in general. This is confusing.

**Comment by timsuchanek** [comment]
clicking outside of popup should just close it if there are no changes made --> window.confirm
