### ISSUE TITLE
FieldPopup: Enum/DateTime List Values default/migration value

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/console#653]

**Comment by marktani** [comment]
I'll leave this ticket here as there are issues in both the UI and the backend.

**Comment by marciobueno1** [comment]
Another consequence is that you have to CANCEL the new filed on the console and start all over again, and need to enter the enum values again because, once it has a default value, you can't DELETE the default value on the console.

**Comment by sorenbs** [comment]
Handling of Default values for list fields of Enum, Json and Datatime values has now been fixed in the backend. The console needs to deliver:

```
Input: [SA,SU] or [SA, SU] Output: ["SA","SU"]
Input: ["2018", "2019"] Output: ["2018-01-01T00:00:00.000Z","2019-01-01T00:00:00.000Z"]
Input: [{"a":4},{"a":5}] Output: [{"a":4},{"a":5}] 

```

See also https://github.com/graphcool/internal-docs/blob/master/default-migration-values_lists.md
