### ISSUE TITLE
Improve breaking change popup wording

### ISSUE THREAD

**Issue by marktani** [graphcool/console#659]
![breaking-change-relation-name](https://cloud.githubusercontent.com/assets/1780597/22689075/90e41ef8-ed2f-11e6-8f8e-4ab0db0341eb.png)

I changed the name to `UserGroups` and the popup warns me that this "will break Relations between AccessGroup and User". A few thoughts:

* if at all, only the relation in question can be broken with this change, not other relations
* what does it mean to break a relation anyway? in this case, renaming the relation breaks client code because the mutation names and arguments change, but the actual relations between the node are not broken. 

The breaking change popup in this case is more confusing than helping I think.

**Update:** I just checked, I have the same thoughts regarding a change of field names.

**Comment by marktani** [comment]
See https://github.com/graphcool/feature-requests/issues/112 for possible improvements

**Comment by timsuchanek** [comment]
Before
Your changes will break Relations between A and B

After
This change might break queries or mutations for this relation in your applications.
