### ISSUE TITLE
Disabling email/pass auth deletes email field

### ISSUE THREAD

**Issue by mruzekw** [graphcool/console#674]
I found this error by trying to authenticate via Auth0. I had both Auth0 and email/pass auth enabled. But for some reason the email field was not available for mutation. Just to narrow things, I decided to disable email/pass auth, and it deleted the email field.

So:
1. `email` was not available for mutation
2. `email` was deleted after disabling email/pass auth

Mutation:
```
mutation ($idToken: String!, $name: String!, $email: String!) {
  createUser(authProvider: {auth0: {idToken: $idToken}}, name: $name, email: $email) {
    id
  }
}
```

Error:
```
{
  "data": null,
  "errors": [
    {
      "message": "Unknown argument 'email' on field 'createUser' of type 'Mutation'. (line 2, column 71):\n  createUser(authProvider: {auth0: {idToken: $idToken}}, name: $name, email: $email) {\n                                                                      ^",
      "locations": [
        {
          "line": 2,
          "column": 71
        }
      ]
    }
  ]
}
```

**Comment by timsuchanek** [comment]
@mruzekw That behavior is intended as when the Email Provider is disabled, the email field is also not needed anymore. But first we should show a proper warning as this is really dangerous and 2nd I'm not sure if we actually need to remove the email.
I will talk with @sorenbs how we can make this experience better for you

**Comment by timsuchanek** [comment]
@mruzekw We already have this Popup in place:
<img width="459" alt="screen shot 2017-02-12 at 6 29 07 pm" src="https://cloud.githubusercontent.com/assets/1094804/22864436/b6de8b54-f151-11e6-8756-ff82be515dd3.png">
Did that show up for you?

**Comment by timsuchanek** [comment]
Cleaning up the issue, if the problem still persists, please comment here
