### ISSUE TITLE
Migrating value uses enum input dialog when changing a float scalar to a float list 

### ISSUE THREAD

**Issue by marktani** [graphcool/console#687]
![migrating-float-fields](https://cloud.githubusercontent.com/assets/1780597/22928964/64f71446-f2b9-11e6-8d43-14f192e4de89.png)

I'm trying to migrate a scalar float field to a list float field. I already have some existing nodes and now I want to provide a migration value. When I click to add the migration value, an input field for enums opens.

**Comment by timsuchanek** [comment]
Looking into it :)
