### ISSUE TITLE
Permission queries are not reloaded correctly when $input_ variable is present

### ISSUE THREAD

**Issue by marktani** [graphcool/console#694]
I define a PQ and save it. When I now open the permission query again, sometimes the displayed query have changed (the query doesn't seem to change in the backend itself). For example when I entered this query:

```graphql
query permitPost($userId: ID!, $new_authorId: ID!) {
  allUsers(filter: {
    AND: [{
      id: $userId
    }, {
      id: $new_authorId
    }]
  }) {
    id
  }
}
```

and I open it later, it might be changed to this:

```graphql
{
  allUsers(filter: {
    AND: [{
      id: $userId
    }, {
      id: $new_authorId
    }]
  }) {
    id
  }
}
```

**Comment by marktani** [comment]
fixed with new PQs

**Comment by jvbianchi** [comment]
I'm having this problem, as described on the [forum](https://www.graph.cool/forum/t/console-not-saving-permission-header/785)

**Comment by marktani** [comment]
Thanks @jvbianchi I could reproduce this.
