### ISSUE TITLE
Mutation Callbacks UI broken

### ISSUE THREAD

**Issue by brene** [graphcool/console#699]
Text is not correctly positioned
![image](https://cloud.githubusercontent.com/assets/4989523/23095594/a15abe00-f60c-11e6-9bef-792feb2f1f0d.png)

Parentheses are white ==> unreadable
![image](https://cloud.githubusercontent.com/assets/4989523/23095598/b22bdfb6-f60c-11e6-8b88-a5bc28b90bac.png)

**Comment by marktani** [comment]
What browser/OS/resolution are you on?

**Comment by brene** [comment]
Chrome + mac + full screen on MBPr 2013

**Comment by timsuchanek** [comment]
What is the state of the ui when it happens? Can't reproduce right now
<img width="1168" alt="screen shot 2017-03-07 at 3 53 44 pm" src="https://cloud.githubusercontent.com/assets/1094804/23661933/567b484c-034e-11e7-8be3-799a61eebbbf.png">
This is how it is supposed to look like
