### ISSUE TITLE
Invalid enum value is directly deleted without prompting

### ISSUE THREAD

**Issue by brene** [graphcool/console#701]
![feb-18-2017 19-06-34](https://cloud.githubusercontent.com/assets/4989523/23095652/6f21c112-f60d-11e6-90c6-5e91cdaaf626.gif)

Repro:
1. Type something starting with a lowercase
2. Hit "space"

**Comment by timsuchanek** [comment]
Due to the lib we're using, a fork of the lib is necessary to accomplish this
