### ISSUE TITLE
Stuck before Onboarding starts

### ISSUE THREAD

**Issue by marktani** [graphcool/console#706]
(The mouse in the gif is distorted, it is actually clicking the buttons)

![](http://im2.ezgif.com/tmp/ezgif-2-64a16f94ad.gif)

Clicking skip or getting started results in "Uncaught in promise (undefined)" error
![screen shot 2017-02-20 at 11 06 55](https://cloud.githubusercontent.com/assets/1780597/23120898/836a4d18-f75e-11e6-8823-83d85397b173.png)

**Comment by timsuchanek** [comment]
Can't reproduce. Reopen when reproducible
