### ISSUE TITLE
Intermittent error in console when loading node

### ISSUE THREAD

**Issue by gmuresan** [graphcool/console#711]
![screen shot 2017-02-23 at 2 15 30 pm](https://cloud.githubusercontent.com/assets/3315803/23275289/f6f11bdc-f9d3-11e6-9f18-4045d8abe538.png)

(Only tested on Chrome)
(Does not happen in incognito mode on Chrome)

In the console, when I click on a different node or refresh the page, I get an error message in the top right corner that says "Blocked a frame with origin "https://console.graph.cool" from accessing a cross-origin frame." The data inside the node fails to load when this error occurs.

If I refresh the page once or twice, it will start working again, but the problem will come back in a few minutes. Sometimes I won't be able to reproduce the issue for a few minutes.

I whitelisted graph.cool on my adblocker and I don't have many other extensions installed. Only started occurring on 2-23-17

**Comment by timsuchanek** [comment]
Can't reproduce right now

**Comment by marktani** [comment]
Some more insights:

> when it happens the most of the time i cannot load node's data. the page is completely loaded but i cannot see the list of nodes with their data

Disabling the Redux DevTools seemed to get rid of the problem, however enabling them again did *not* make the problem occur again.

**Comment by marktani** [comment]
Issues in combination with the Redux DevTools have been confirmed. For now a workaround for this issue is to disable them.
