### ISSUE TITLE
Sentry - Blocked a frame (cross-origin)

### ISSUE THREAD

**Issue by marktani** [graphcool/console#726]
<img width="332" alt="blocked-cors-frame" src="https://cloud.githubusercontent.com/assets/1780597/23413663/9c8fc198-fdd9-11e6-88c0-8dea5017df2a.png">

<img width="1273" alt="sentry" src="https://cloud.githubusercontent.com/assets/1780597/23414009/c730324c-fdda-11e6-828d-bb1e8eafbb85.png">

<img width="1307" alt="sentry2" src="https://cloud.githubusercontent.com/assets/1780597/23414028/d7708986-fdda-11e6-8a02-ffcc5be53a9f.png">

**Comment by timsuchanek** [comment]
Can't reproduce right now

**Comment by timsuchanek** [comment]
Dup of #711
