### ISSUE TITLE
Settings > Billing/Team load blocked by raven/sentry

### ISSUE THREAD

**Issue by abefetterman** [graphcool/console#728]
Settings > Billing and Settings > Team don't load due to error in raven.js and overload on sentry.io API calls.

billing: Uncaught TypeError: Cannot read property 'name' of undefined (raven.js:381)
team: Uncaught TypeError: Cannot read property 'maxSeats' of undefined (raven.js:381)
sentry: POST https://sentry.io/api/135786/store/?sentry_version=7&sentry_client=raven-js%2F3.10.0&sentry_key=f4b2d5e7865742e290a3bf77849d5e4a 429 (TOO MANY REQUESTS)

<img width="561" alt="screen shot 2017-03-02 at 9 41 09 am" src="https://cloud.githubusercontent.com/assets/766710/23519646/8850744e-ff2c-11e6-9594-7e84ed83c93f.png">
<img width="562" alt="screen shot 2017-03-02 at 9 41 03 am" src="https://cloud.githubusercontent.com/assets/766710/23519644/884f57bc-ff2c-11e6-8714-1adf6a6421a7.png">
<img width="563" alt="screen shot 2017-03-02 at 9 40 43 am" src="https://cloud.githubusercontent.com/assets/766710/23519645/884f6dec-ff2c-11e6-872b-997f5fed5330.png">
<img width="562" alt="screen shot 2017-03-02 at 9 40 31 am" src="https://cloud.githubusercontent.com/assets/766710/23519643/884f484e-ff2c-11e6-973a-370074c9019d.png">

**Comment by abefetterman** [comment]
FYI, this was due to having a space in the project name. I believe it is still a bug you want to fix.

**Comment by marktani** [comment]
Thanks for the report, we identified the issue and fixed it :slightly_smiling_face:
