### ISSUE TITLE
ensure `x-graphcool-source` header is always set correctly

### ISSUE THREAD

**Issue by sorenbs** [graphcool/console#730]
https://github.com/graphcool/console/search?utf8=%E2%9C%93&q=x-graphcool-source

It seems like this header is currently not being set for:

- [x] Databrowser
- [x] Playground

**Comment by sorenbs** [comment]
While we're at it, we should change the header value from `dashboard:[sub component]` to `console:[sub component]`

**Comment by schickling** [comment]
@timsuchanek please re-publish `graphcool-graphiql` and upgrade the dep here.
