### ISSUE TITLE
Getting Started Experience

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/console#753]
- [x] Playground too small - Collapse Sidenav
- [x] GraphiQL autocompletion doesn't close
- [x] Docs are hidden sometimes, can't expand them
- [x] Fix hover state of fields in databrowser
- [x] GraphiQL multiselect play: first time selection doesn't work
- [x] allow leaving databrowser when nothing changed

**Comment by marktani** [comment]
Field name for `description` is not checked, using `desctiption` (note there's no r) you can continue until the step in the playground where the `allPost` query won't be accepted because of the typo.
