### ISSUE TITLE
Redux is in dev mode

### ISSUE THREAD

**Issue by marktani** [graphcool/console#765]
> You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

**Comment by heymartinadams** [comment]
`Mutation Callbacks` are sometimes not displaying correctly. Received that same error message in Chrome dev console. Also received this warning in the dev console:
```
Server request for query `ActionBoxes_ActionRelayQL` failed for the following reasons:

1. Can't find appropriate subtype for field at path node (line 1, column 45):
query ActionBoxes_ActionRelayQL($id_0:ID!) {node(id:$id_0) {id,__typename,...F0}} fragment F0 on Action {id,description,triggerType,handlerType,triggerMutationModel {model {id,name},mutationType,fragment,id},handlerWebhook {url,id}}
                                            ^
   RelayQL($id_0:ID!) {node(id:$id_0) {id,__typename,...F0}} fr
                       ^^^
```

**Comment by marktani** [comment]
Looks like the problem with mutation callbacks is a separate issue. I created a new ticket: https://github.com/graphcool/api-bugs/issues/27

**Comment by timsuchanek** [comment]
The problem is that the graphql-voyager build is not done properly, pull request submitted:
https://github.com/APIs-guru/graphql-voyager/pull/17
