### ISSUE TITLE
Scrollbars in permissions page

### ISSUE THREAD

**Issue by Samuell1** [graphcool/console#811]
Hey,
in Firefox 52, Win 10 is there scrollbars in permissions page under Fields

![obrazok](https://cloud.githubusercontent.com/assets/3110002/24768850/7c653036-1b04-11e7-8700-f915d7b72017.png)

I found there is class `overflowXScroll ` with `scroll`, i changed to `auto` and its fixed for me

**Comment by timsuchanek** [comment]
Thanks @Samuell1 for reporting that! Just did exactly what you proposed
