### ISSUE TITLE
Subscriptions not listening

### ISSUE THREAD

**Issue by TheoMer** [graphcool/console#824]
_OS: Windows 10 Pro
Browser: Google chrome Version 56.0.2924.87 (64-bit) and Opera 44.0.2510.857 (PGO)_

So, activating the following subscription:

```
subscription followDeletedUpdatedCreatedComment {
  Comments (
    filter: {
      mutation_in: [UPDATED]
      updatedFields_contains: "deleted"
    }
  ) {
    mutation
    node {
      id
     	deleted
    }
    updatedFields
    previousValues {
     	id
      deleted
    }
  }
}
```

causes the following output to immediately appear in the results window (See image):

```
{
  "data": null
}
```

![subscriptions_isse](https://cloud.githubusercontent.com/assets/15969262/24930954/52628e66-1f03-11e7-9c4e-59cafaf9de72.jpg)

Even though 'Listening' appears on the screen, running the following mutation does not result in any subscription alert:

```
  mutation updateCommentsMutation ($id: ID!) {
    updateComments(id: $id, deleted: true) {
      id
      deleted
      posts {
        id
      }
    }
  }
```

What is the issue here

**Comment by marktani** [comment]
You can investigate subscription errors like this in the network tab. In this case, the problem stems from the fact that you use `updatedFields_contains` together with `CREATED` and `DELETED`.

From [the docs](https://www.graph.cool/docs/reference/simple-api/combining-subscriptions-kengor9ei3/#advanced-subscription-filters):

> Note: Using any of the updatedFields filter conditions together with CREATED or DELETED subscriptions results in an error.

Here's what you can do instead:

```graphql
subscription followDeletedUpdatedCreatedComment {
  Comments (
    filter: {
      OR: [{
        mutation_in: [CREATED, DELETED]  
      }, {
        mutation_in: [UPDATED]
        updatedFields_contains: "deleted"
      }]
    }
  ) {
    mutation
    node {
      id
     	deleted
    }
    updatedFields
    previousValues {
     	id
      deleted
    }
  }
}
```

Also:

> Note: previousValues is null for CREATED subscriptions and updatedFields is null for CREATED and DELETED subscriptions.

**Comment by TheoMer** [comment]
Where is the 'network' tab situated, I can't see one on my console?

Unfortunately. The subscription still fires no alerts, when running the following mutation:

```
  mutation removeComment ($id: ID!, $cid: ID!) {
    removeFromPostsOnComments (postsPostsId: $id, commentsCommentsId: $cid) {
      postsPosts {
        __typename
        id
        comments {
          __typename
          id
          text
          user
          deleted
          posts {
            __typename
            id
          }
        }
      }
    }

    deleteComments(id: $cid) {
      id
    }
  }
```

**Comment by TheoMer** [comment]
For reference purposes, my ApolloClient is as follows:

import ApolloClient, {
  createNetworkInterface,
  addTypeName,
} from 'apollo-client';

import { 
    SubscriptionClient, 
    addGraphQLSubscriptions 
} from 'subscriptions-transport-ws'

// Create WebSocket client
const wsClient = new SubscriptionClient('wss://subscriptions.graph.cool/v1/myEndPoint', {
  reconnect: true,
  connectionParams: {
    // Pass any arguments you want for initialization
  }
})
const networkInterface = createNetworkInterface({ 
  uri: 'https://api.graph.cool/simple/v1/myEndPoint' 
})

// Extend the network interface with the WebSocket
const networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
  networkInterface,
  wsClient
)

const client = new ApolloClient({
  networkInterface: networkInterfaceWithSubscriptions,
  dataIdFromObject: (o) => o.id,
   addTypeName: true
})

export default client;

**Comment by marktani** [comment]
Can you try to run the two mutations independently from each other?

**Comment by TheoMer** [comment]
Yes, as follows:

```
  mutation removeComment ($id: ID!, $cid: ID!) {
    removeFromPostsOnComments (postsPostsId: $id, commentsCommentsId: $cid) {
      postsPosts {
        __typename
        id
        comments {
          __typename
          id
          text
          user
          deleted
          posts {
            __typename
            id
          }
        }
      }
    }
  }
  
  mutation deleteComment ($cid: ID!) {
    deleteComments(id: $cid) {
      id
    }
  }

{
  "id": "cj0qotlssddd10111dow8mma4",
  "cid": "cj0qovo81de4l0111adekywi4"
}
```

But still subscriptions are not firing.

**Comment by marktani** [comment]
After some investigation this seems to be a problem related to the subscription schema, I'll move the issue over here: https://github.com/graphcool/api-bugs/issues/38.
