### ISSUE TITLE
Small CSS bug in the project menu

### ISSUE THREAD

**Issue by dubstrike** [graphcool/console#837]
<img width="289" alt="screen shot 2017-04-17 at 9 00 13 pm" src="https://cloud.githubusercontent.com/assets/6843656/25100582/f51bf1a4-23b0-11e7-9924-e5c37ab2926e.png">
<img width="288" alt="screen shot 2017-04-17 at 9 00 20 pm" src="https://cloud.githubusercontent.com/assets/6843656/25100586/f73f5566-23b0-11e7-8496-87836eb816c5.png">

After expanding the menu, there is a leftover dark gradient.

**Comment by timsuchanek** [comment]
Thanks for reporting @dubstrike !
Can you specify in which browser and os you have the issue?
Thanks!
![image](https://user-images.githubusercontent.com/1094804/27011922-c85fec56-4ec6-11e7-9ee1-19cd9e2ca5b1.png)

**Comment by dubstrike** [comment]
I believe this has already been fixed way back in April.

**Comment by marktani** [comment]
Thanks!
