### ISSUE TITLE
Improve usage of select node popup when creating a node

### ISSUE THREAD

**Issue by marktani** [graphcool/console#839]
When creating a new node and opening the select node popup for the one-side of a relation, the popup will never contain any elements, even though some already exist.

Example, you're creating a new post node and want to select the author. There are already 5 users.
The select node popup for the author field doesn't contain any users yet though.

This is not an issue for a many-side of a relation, because it there says "Should be added later"... Maybe this should be added as well?

**Comment by marktani** [comment]
The fact that there is a popup available but doesn't contain any nodes when creating a node is very, very confusing. 🙂

**Comment by timsuchanek** [comment]
seems solved
