### ISSUE TITLE
Algolia warning is confusing to users unfamiliar with Algolia

### ISSUE THREAD

**Issue by marktani** [graphcool/console#855]
> on UX of that popup: As a user never worked with the integration: I really have no idea what that "6 Operations" means. So the message is not very usefull at all. Also it make me feel doing something wrong while I was doing fine.

**Comment by lucfranken** [comment]
In addition to this one:

> Usage warning: Note that all nodes will be resynced.....


Try writing a longer graphql statement in the query box (like 15-20 lines). There is a warning constantly popping over your query while writing. With no possibility to dismiss the popup. Really frustrating to enter a query like that.

FYI: Using a Macbook. Maybe your tests are done on bigger screens.

The warning itself is ok and clear. In this step (when modifying a query) I understand the message and it's useful. Maybe it should only shown when having > 100 / 1000 changes or something. Anyway it should not pop over the query input.
<img width="494" alt="schermafbeelding 2017-05-04 om 08 34 26" src="https://cloud.githubusercontent.com/assets/1609379/25692639/83ad668c-30a4-11e7-856a-7691c39b9830.png">
