### ISSUE TITLE
Don't override browser default search in data explorer.

### ISSUE THREAD

**Issue by ilionic** [graphcool/console#863]
Currently when pressing `cmd+f` opens graph.cool own search which is useful for filtering, but
I would expect to open browser default search ( for focusing on fields in bigger models etc. )

**Comment by marktani** [comment]
There's still a difference between `cmd+f` and the searchbox - the databrowser doesn't list all your nodes (I believe we only list the first 50 or 100 nodes), so the searchbox will search through **all** nodes while `cmd+f` can only search the displayed nodes.

But I can see how this behaviour is irritating. Thanks for the suggestion!
