### ISSUE TITLE
Playground Docs need a scrollbar

### ISSUE THREAD

**Issue by marktani** [graphcool/console#867]
> I have a tiny comment regarding the documentation on the right hand side in the playground page
I need a scroll-bar when there is a lot of content in this section because the data is there but not visible. I was forced to adjust the css in the inspector (by adding a fixed height and overflow: scroll) to the full documentation

**Comment by hossam-maurice** [comment]
I am facing this issue and another scrolling issue in schema page in the both sections of "schema-wrapper". These issues exists only on **firefox** browser.
