### ISSUE TITLE
Display issue when setting default value for new integer field

### ISSUE THREAD

**Issue by sedubois** [graphcool/console#869]
<img width="562" alt="screen shot 2017-04-27 at 13 43 39" src="https://cloud.githubusercontent.com/assets/4217871/25480007/9c6afe32-2b4f-11e7-93c8-0250698d4824.png">

**Comment by marktani** [comment]
To be clear, it's still possible to set the default value by clicking the "invisible" input field right to "null" and entering digits :slightly_smiling_face: The UX is horrible though...
