### ISSUE TITLE
Data for a particular required field is discarded when creating node

### ISSUE THREAD

**Issue by sedubois** [graphcool/console#870]
I have a Track model with a slug String! field (required). But when I try to create a new node in the data browser and enter a value for this field then move focus to next field with tab (which should save this data), 
1. the data is discarded and
2. I'm able to create the node, regardless of the unmet constraint

![capture](https://cloud.githubusercontent.com/assets/4217871/25491760/91f235ae-2b79-11e7-94d6-9be7214852f4.gif)

Then I need to go back to the created node and enter the value afterwards. So there seems to be a bug, and also it's rather cumbersome.

Thanks for your attention and keep up the good work 🙂

**Comment by marktani** [comment]
This seems to be the reproduction for #838, thanks for the detailed bug report!
