### ISSUE TITLE
The default value of a field is preserved when changing its type

### ISSUE THREAD

**Issue by do4gr** [graphcool/console#893]
Changing a field that has a default value set to another type hides the fact that it has a default value. If the types are incompatible the console will throw an error with the now invalid default value, but the user cannot see the default value unless he switches back to the original type. 

If the types are compatible, for example boolean -> string no default value will be displayed after the change to string, but it is still there.

**Comment by marktani** [comment]
Here's a video for easy reproduction: https://www.dropbox.com/s/ybzx4l6z7ptbe3m/stored-default-value.mov?dl=0

**Comment by timsuchanek** [comment]
This is a backend issue. Will create an issue there
