### ISSUE TITLE
Algolia export nested object on sync

### ISSUE THREAD

**Issue by lucfranken** [graphcool/console#898]
This is my export to Algolia which works fine:

```graphql
{
    node {
      id
      name
    }
  }
```

I change it to:

```graphql
{
    node {
      id
      name
      photos {
        id
        url
      }
    }
  }
```

I already had in my graph: The node with name and the associated photos (one node can contain many photos).

I expect: I can access the photo url after the initial sync.

Actual result in Algolia: photos = null

<img width="138" alt="schermafbeelding 2017-05-04 om 11 00 09" src="https://cloud.githubusercontent.com/assets/1609379/25696817/dd759c2a-30b8-11e7-8ad2-13f9268c7361.png">

Now I edit name in GraphCool. This instantly updates Algolia (great stuff!)

Now it's synced:

<img width="227" alt="schermafbeelding 2017-05-04 om 11 06 06" src="https://cloud.githubusercontent.com/assets/1609379/25697028/b6d60c16-30b9-11e7-8e0e-a64cbba2017a.png">

So it seems the initial sync did not sync the nested one at first, while a forced sync does. 

To be clear: The photos did exists long before I added the photos field into the sync graphql.

Edit: After some more testing this behavior is consistent. If you need more info about which nodes it happens exactly feel free to send a dm.

**Comment by marktani** [comment]
Thanks for the report, I transfered it over to the [API bugs repo](https://github.com/graphcool/api-bugs/issues/52).

**Comment by lucfranken** [comment]
Cool! :)

It's unclear where to post bugs, mostly because that repo does not have for example a readme. Expo for example decided to group them all in one central repo and added a template for issues: https://github.com/expo/xdl/issues/new
