### ISSUE TITLE
Adding enum confusing, results in endless loading

### ISSUE THREAD

**Issue by marktani** [graphcool/console#910]
* it's possible to [save enums without specifying a value](https://www.dropbox.com/s/b022gqtda6v4a06/saving-enums-without-values.mov?dl=0) - resulting in infinite loading

* when typing an enum name, it's not clear that you need to hit enter/space to confirm it. When [you only want to create one value](https://www.dropbox.com/s/me6zxaohgxpzhc4/saving-one-enum-value.mov?dl=0), you run into the same problem as above.

**Comment by marktani** [comment]
This is a common pitfall and happens frequently.

**Comment by timsuchanek** [comment]
Still not the perfect ux flow, but we now show a proper error when the values are missing and don't end in the infinite loop anymore
