### ISSUE TITLE
Function: trigger info missing for RP

### ISSUE THREAD

**Issue by sorenbs** [graphcool/console#929]
When updating RP function I can not change trigger information (type and mutation) and I also cannot see the current trigger info. As this is also not available in the functions overview I am kinda lost

![image](https://cloud.githubusercontent.com/assets/281337/26028725/87ca44cc-3826-11e7-8410-300bf408d207.png)

**Comment by marktani** [comment]
This goes back to https://github.com/graphcool/ui-feedback/issues/4, but in this case it's especially unfortunate 🙂
