### ISSUE TITLE
Permission Query area should be highlighted automatically

### ISSUE THREAD

**Issue by ndresx** [graphcool/console#964]
The Permission Query field stays inactive although the cursor already appears in the code area. This seems to be fine, however I think it would be better to remove the inactive state as soon as the user starts typing (without having to click into that area).
![graphcool-console-permission-query](https://cloud.githubusercontent.com/assets/27507295/26128367/7e8c5b62-3a8c-11e7-9373-dcab6e92c783.jpg)

_By the way, it looks great!_

**Comment by timsuchanek** [comment]
@ndresx that is indeed a great UX idea. We will implement it soon :)
