### ISSUE TITLE
Editing relation type in schema does not work

### ISSUE THREAD

**Issue by sedubois** [graphcool/console#979]
The schema editor (which looks cool BTW 😎) allows to edit its text directly, but nothing happens when I click Preview Changes then Apply Changes. (e.g after having edited a relation name in the two locations where it is used)

I renamed some types and I need to rename the relation types accordingly, but because of this it seems it isn't possible right now.

**Comment by timsuchanek** [comment]
Thanks @sedubois we will look into it and make sure it not only looks cool :)

**Comment by sorenbs** [comment]
@sedubois Would you be able to provide an example schema before/after that has this issue?

**Comment by timsuchanek** [comment]
As this issue is now added to `graphcool/backend-apis`, I'm closing this here
