### ISSUE TITLE
Adding field in schema editor does not work

### ISSUE THREAD

**Issue by sedubois** [graphcool/console#980]
I tried to add a field (`position: Int! @isUnique @defaultValue(value: 0) @migrationValue(value: 0)`) to one of my types, but then get this when submitting my changes:

<img width="450" alt="screen shot 2017-05-19 at 8 50 24" src="https://cloud.githubusercontent.com/assets/4217871/26236375/5e0a1db2-3c70-11e7-91e4-fac0a484f141.png">

Although I haven't touched `titleEn` and `slug` (they are still visible). 

NB: it would also help if the schema editor displayed the text diff, to under what's going on.

**Comment by timsuchanek** [comment]
Thanks for reporting! Will look into it

**Comment by sorenbs** [comment]
@sedubois Would you be able to provide a minimal example before/after that shows this issue?

Thanks a lot for reporting these issues - we'll get them sorted asap!

**Comment by timsuchanek** [comment]
As this issue is now added to `graphcool/backend-apis`, I'm closing this here
