### ISSUE TITLE
Can't set migration value for required field

### ISSUE THREAD

**Issue by sedubois** [graphcool/console#981]
I try to create a new field `position` on type `Course` using the wizard. 

- no problem in the Base Settings, can enter the name and select INT
- in advanced options however, I then select Required but then can't set a default value (goes back to null every time) and the migration value is required although this is a new field

<img width="556" alt="screen shot 2017-05-19 at 8 58 19" src="https://cloud.githubusercontent.com/assets/4217871/26236572/52761e0a-3c71-11e7-9986-3a1f57ec4506.png">

I managed to workaround by not making the field required, but obviously I would like to have that constraint asap.

**Comment by marktani** [comment]
The migration value is required because you already have data and it's a required field - so the existing nodes need to have some value for the new field.

What do you mean, the default value goes to null everyime? How are you trying to set it?

**Comment by sedubois** [comment]
@marktani Indeed I was incorrect to say that the migration value wasn't needed. But anyway I'm not able to put a migration value. When I type a value there then hit enter or click outside the text box, the value isn't taken into account.

**Comment by timsuchanek** [comment]
Fixed
