### ISSUE TITLE
Export is missing directives for isUnique and relation

### ISSUE THREAD

**Issue by lucfranken** [graphcool/console#982]
It seems in the export some directives are missing:

https://github.com/apollographql/apollo-codegen/issues/118#issuecomment-302415550

@martijnwalraven 

> The Unknown directive message comes from graphql-js, not from apollo-codegen. This is due to a built-in validation rule that checks whether a directive is valid for a particular schema and AST location, see here.
> 
> Custom directives will have to be included in the schema, and they don't seem to be part of the introspection query result you get from the Graphcool endpoint. Maybe you could post on the Graphcool Slack to ask about this, and point them to this issue?

Code to run from terminal to reproduce the error:

```bash
$ apollo-codegen introspect-schema https://api.graph.cool/simple/v1/cj2ughqytctr20169wr8ag4tv --output schema.json
$ apollo-codegen generate **/*.graphql --schema schema.json --target flow --output schema.flow.js
Unknown directive "isUnique".
Unknown directive "relation".
```

**Comment by timsuchanek** [comment]
Thanks for reporting @lucfranken ! Will look into it

**Comment by timsuchanek** [comment]
As this issue is now added to `graphcool/backend-apis`, I'm closing this here
