### ISSUE TITLE
using different auth0 providers creates duplicate users for same email

### ISSUE THREAD

**Issue by vgrafe** [graphcool/console#983]
Hi! 

When using auth0 to manage authentication, if I sign up with say google then later on with email/password, the token returned is different, so the following query (used to fetch the authenticated user’s data on graph.cool’s db) returns nothing, even if an user was created with the first token. 

```
  query {
    user {
      id
      name
    }
  }
```

I guess that changing that query to the following solves the problem and avoids creating a new record. But is this the good approach? 

```
{
  allUsers(filter: {emailAddress: $email}) {
    id
    name
  }
}
```

Am I missing something earlier on?

**Comment by marktani** [comment]
Thanks for your question @vgrafe! This repository is about problems in the Console itself - could you please post it to the forum: https://www.graph.cool/forum/c/platform?

Thanks! 🙌

**Comment by vgrafe** [comment]
will do, sorry!

**Comment by marktani** [comment]
Thanks for migrating your question, I'm closing the issue here 🙂
