### ISSUE TITLE
Scroll bar on schema view doesn't work on Firefox

### ISSUE THREAD

**Issue by marktani** [graphcool/console#988]
> The scroll bar of the types in the schema page, doesn't work. I'm using Mozilla Firefox on Win 10.

**Comment by Samuell1** [comment]
There is some gif example of that scroll bar bug:

![d7sjh6by](https://cloud.githubusercontent.com/assets/3110002/26760746/ebe58146-4920-11e7-8e9e-02e4f28c5793.gif)
