### ISSUE TITLE
Can't set field as required

### ISSUE THREAD

**Issue by sedubois** [graphcool/console#993]
I have a type `Author` with field `position`. I try to set the field as required using the wizard, then it asks for the migration value, but the value isn't accepted when submitting the text box, with no error message. So I can't validate/apply the change.

Related to #981

**Comment by marktani** [comment]
What's the field type, and what value are you trying to enter? What do you mean the value is not accepted?

**Comment by sedubois** [comment]
I mean that nothing happens when I hit enter or click outside the field. The field type is `Int` and I put the value `0`.

**Comment by marktani** [comment]
I remember you told me that this was a problem when the field is set to unique, is that correct?
