### ISSUE TITLE
Missing Input Type and Others

### ISSUE THREAD

**Issue by nosykretts** [graphcool/console#997]
![screen shot 2017-05-24 at 1 28 33 am](https://cloud.githubusercontent.com/assets/2125103/26367890/ad5dc7be-4022-11e7-891b-d72858ec9b01.png)
![screen shot 2017-05-24 at 1 29 41 am](https://cloud.githubusercontent.com/assets/2125103/26367891/ad5f24d8-4022-11e7-88c3-d5e876a4a1dd.png)
![screen shot 2017-05-24 at 1 37 06 am](https://cloud.githubusercontent.com/assets/2125103/26367892/ad6196dc-4022-11e7-8bb3-2dd45a1ff220.png)
![screen shot 2017-05-24 at 1 41 40 am](https://cloud.githubusercontent.com/assets/2125103/26367893/ad6a8c38-4022-11e7-9282-d929b1d3182b.png)

**Comment by marktani** [comment]
Hey @nosykretts, could you try to hard refresh (cmd-shift-r) and try again? I can't reproduce this anymore.

**Comment by nosykretts** [comment]
Problem fixed. Thanks

**Comment by timsuchanek** [comment]
Thank you @nosykretts !
